# Generated by Django 4.0 on 2024-01-27 06:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_alter_category_priority_and_more'),
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'связь корзина-блюдо',
                'verbose_name_plural': 'связи корзина-блюдо',
                'ordering': ['cart'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('WCO', 'ожидает подтверждения'), ('INA', 'недоступен'), ('CFD', 'подтвержден'), ('PYD', 'оплачен'), ('RTN', 'оформлен возврат'), ('RDY', 'готов'), ('HDY', 'передан в доставку'), ('DLD', 'доставлен'), ('CLD', 'выдан')], default='WCO', max_length=3, verbose_name='Статус')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='стоимость доставки')),
                ('recipient_name', models.CharField(max_length=400, verbose_name='получатель')),
                ('recipient_phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('recipient_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('time', models.CharField(blank=True, max_length=100, null=True, verbose_name='время доставки')),
                ('comment', models.CharField(blank=True, help_text='Комментарий к заказу.', max_length=400, null=True, verbose_name='Комментарий')),
                ('persons_qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Кол-во приборов')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='сумма заказа до скидки, DIN')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Скидка, DIN')),
                ('discounted_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Сумма заказа после скидок, DIN')),
                ('final_amount_with_shipping', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Сумма заказа с учетом скидок и доставки, DIN')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'заказ-блюдо',
                'verbose_name_plural': 'заказ-блюдо',
                'ordering': ['dish'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID устройства')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('complited', models.BooleanField(default=False, verbose_name='Заказана')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма, DIN')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Скидка, DIN')),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Итог сумма, DIN')),
                ('dishes', models.ManyToManyField(help_text='Добавьте блюда в корзину.', through='shop.CartDish', to='catalog.Dish', verbose_name='Товары в корзине')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'корзина покупок',
                'verbose_name_plural': 'корзины покупок',
                'ordering': ['-created'],
            },
        ),
    ]
