# Generated by Django 4.0 on 2023-12-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shopping_cart', serialize=False, to='users.baseprofile', verbose_name='Клиент')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('complited', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(default=0, max_length=9)),
                ('items_num', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во')),
                ('dishes', models.ManyToManyField(help_text='Добавьте блюда в заказ.', through='shop.CartDish', to='catalog.Dish', verbose_name='Товары в заказе')),
            ],
            options={
                'verbose_name': 'корзина покупок',
                'verbose_name_plural': 'корзины покупок',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='orderdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.dish', verbose_name='Товары в заказе'),
        ),
        migrations.AddField(
            model_name='orderdish',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_dishes', to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.delivery', verbose_name='доставка'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(help_text='Добавьте блюда в заказ.', through='shop.OrderDish', to='catalog.Dish', verbose_name='Товары в заказе'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='заказы', to='shop.shop', verbose_name='точка'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.baseprofile', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='cartdish',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_dishes', to='shop.shoppingcart', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='cartdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_carts', to='catalog.dish', verbose_name='Товары в корзине'),
        ),
        migrations.AddConstraint(
            model_name='orderdish',
            constraint=models.UniqueConstraint(fields=('dish', 'order'), name='unique_dish_order'),
        ),
        migrations.AddConstraint(
            model_name='cartdish',
            constraint=models.UniqueConstraint(fields=('dish', 'cart'), name='unique_dish_cart'),
        ),
    ]
