# Generated by Django 4.0 on 2024-02-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_dishcategory_dish'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdish',
            name='base_profile',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Запись  в БД'),
        ),
        migrations.AddField(
            model_name='cartdish',
            name='cart_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Запись блюда в БД'),
        ),
        migrations.AddField(
            model_name='cartdish',
            name='dish_article',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Запись блюда в БД'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartdishes', to='catalog.dish', verbose_name='Товары в корзине'),
        ),
    ]
