# Generated by Django 4.0 on 2024-02-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('catalog', '0002_alter_categorytranslation_messenger_name_and_more'),
        ('delivery_contacts', '0004_alter_delivery_default_delivery_cost_and_more'),
        ('promos', '0002_remove_promonews_image_sr_promonews_image_sr_latn'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.baseprofile', verbose_name='ID клиента'),
        ),
        migrations.AddField(
            model_name='orderdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.dish', verbose_name='Товары в заказе'),
        ),
        migrations.AddField(
            model_name='orderdish',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dishes', to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_contacts.delivery', verbose_name='доставка'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery_contacts.deliveryzone', verbose_name='зона доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(help_text='Добавьте блюда в заказ.', through='shop.OrderDish', to='catalog.Dish', verbose_name='Товары в заказе'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='заказы', to='delivery_contacts.restaurant', verbose_name='точка'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.baseprofile', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='cartdish',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartdishes', to='shop.shoppingcart', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='cartdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartdishes', to='catalog.dish', verbose_name='Товары в корзине'),
        ),
        migrations.AddConstraint(
            model_name='orderdish',
            constraint=models.UniqueConstraint(fields=('dish', 'order'), name='unique_dish_order'),
        ),
        migrations.AddConstraint(
            model_name='cartdish',
            constraint=models.UniqueConstraint(fields=('dish', 'cart'), name='unique_dish_cart'),
        ),
    ]
