# Generated by Django 4.0 on 2024-04-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0009_alter_deliveryzone_polygon'),
        ('catalog', '0007_alter_dish_article_alter_dish_final_price_and_more'),
        ('promos', '0002_alter_promocode_options_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True, verbose_name='тип скидки')),
                ('discount_perc', models.DecimalField(blank=True, decimal_places=2, help_text="Внесите скидку, прим. для 10% внесите '10,00'.", max_digits=7, null=True, verbose_name='Скидка в %')),
                ('discount_am', models.DecimalField(blank=True, decimal_places=2, help_text="Внесите скидку, прим. '300,00'.", max_digits=7, null=True, verbose_name='Скидка в RSD')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Окончание действия')),
                ('title_rus', models.CharField(max_length=100, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'discount',
                'verbose_name_plural': 'discounts',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cartdish',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartdishes', to='shop.shoppingcart', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='cartdish',
            name='dish',
            field=models.ForeignKey(help_text='Начните писать название блюда...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartdishes', to='catalog.dish', verbose_name='Товары в корзине *'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'admin')], help_text='Кем создан заказ (клиент / админ).', null=True, verbose_name='кем создан'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_contacts.delivery', verbose_name='доставка *'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery_contacts.deliveryzone', verbose_name='зона доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(help_text='Добавьте блюда в заказ.', through='shop.OrderDish', to='catalog.Dish', verbose_name='Товары в заказе'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=1, help_text='Подтянется автоматически.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='заказы', to='delivery_contacts.restaurant', verbose_name='точка '),
        ),
    ]
