# Generated by Django 4.0 on 2024-02-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartdish_base_profile_cartdish_cart_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdish',
            name='base_profile',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Запись baseprofile в БД'),
        ),
        migrations.AddField(
            model_name='orderdish',
            name='dish_article',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Запись блюда в БД'),
        ),
        migrations.AddField(
            model_name='orderdish',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Запись заказа в БД'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='base_profile',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Запись baseprofile в БД'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartdishes', to='shop.shoppingcart', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='cart_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Запись корзины в БД'),
        ),
    ]
