# Generated by Django 4.0 on 2024-03-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='тип скидки')),
                ('discount_perc', models.DecimalField(blank=True, decimal_places=2, help_text="Внесите скидку, прим. для 10% внесите '10,00'.", max_digits=7, null=True, verbose_name='Скидка в %')),
                ('discount_am', models.DecimalField(blank=True, decimal_places=2, help_text="Внесите скидку, прим. '300,00'.", max_digits=7, null=True, verbose_name='Скидка в RSD')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Окончание действия')),
                ('title_rus', models.CharField(max_length=100, verbose_name='jgbcfybt')),
            ],
        ),
    ]
