# Generated by Django 4.0 on 2024-02-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время доставки'),
        ),
    ]
