# Generated by Django 4.0 on 2024-04-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('shop', '0002_discount_cartdish_cart_cartdish_dish_and_more'),
        ('catalog', '0007_alter_dish_article_alter_dish_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Поиск по имени и номеру телефона.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.baseprofile', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='orderdish',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderdishes', to='catalog.dish', verbose_name='Товары в заказе'),
        ),
        migrations.AddField(
            model_name='orderdish',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdishes', to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Поиск в поле по имени и номеру телефона.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.baseprofile', verbose_name='ID клиента'),
        ),
        migrations.AddConstraint(
            model_name='cartdish',
            constraint=models.UniqueConstraint(fields=('dish', 'cart'), name='unique_dish_cart'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_number', 'created'), name='unique_order_number_created'),
        ),
        migrations.AddConstraint(
            model_name='orderdish',
            constraint=models.UniqueConstraint(fields=('dish', 'order'), name='unique_dish_order'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('type', 'title_rus'), name='unique_type_title_rus'),
        ),
    ]
