# Generated by Django 4.0 on 2024-02-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdish',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='сумма заказа до скидки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Скидка, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Сумма заказа после скидок, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount_with_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Сумма заказа с учетом скидок и доставки, DIN'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
