# Generated by Django 4.0 on 2023-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdish',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
