# Generated by Django 4.0 on 2024-01-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_recipient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='items_qty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Кол-во порций, шт'),
        ),
    ]
