# Generated by Django 4.0 on 2024-03-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['id'], 'verbose_name': 'discount', 'verbose_name_plural': 'discounts'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='title_rus',
            field=models.CharField(max_length=100, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(max_length=20, unique=True, verbose_name='тип скидки'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('type', 'title_rus'), name='unique_type_title_rus'),
        ),
    ]
