# Generated by Django 4.0 on 2024-04-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_useraddress_comment_useraddress_flat_and_more'),
        ('shop', '0004_rename_amount_orderdish_unit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='my_delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.useraddress', verbose_name='Адрес из моих адресов'),
        ),
    ]
