# Generated by Django 4.0 on 2024-02-25 17:33

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_delivery_db_order_delivery_zone_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(max_length=400, validators=[users.validators.validate_first_and_last_name], verbose_name='имя получателя'),
        ),
    ]
