# Generated by Django 4.0 on 2024-01-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shoppingcart_items_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_qty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Кол-во ед-ц заказа, шт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к заказу.', max_length=400, null=True, verbose_name='Комментарий'),
        ),
    ]
