# Generated by Django 4.0 on 2023-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderdish_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdish',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
