# Generated by Django 4.0 on 2024-04-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_my_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='manual_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='auth_fst_ord_disc_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рассчитывается автоматически.', max_digits=8, null=True, verbose_name='скидка за первый заказ, DIN'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode_disc_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рассчитывается автоматически.', max_digits=8, null=True, verbose_name='скидка по промокоду, DIN'),
        ),
        migrations.AddField(
            model_name='order',
            name='takeaway_disc_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рассчитывается автоматически.', max_digits=8, null=True, verbose_name='скидка за первый заказ, DIN'),
        ),
    ]
