# Generated by Django 4.0 on 2023-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderdish_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rus', models.CharField(max_length=100, verbose_name='заголовок рус')),
                ('full_text_rus', models.CharField(max_length=600, verbose_name='описание рус')),
                ('title_eng', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок eng')),
                ('full_text_eng', models.CharField(blank=True, max_length=600, null=True, verbose_name='описание eng')),
                ('title_srb', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок srb')),
                ('full_text_srb', models.CharField(blank=True, max_length=600, null=True, verbose_name='описание srb')),
            ],
            options={
                'verbose_name': 'промо-новость',
                'verbose_name_plural': 'промо-новости',
            },
        ),
    ]
