# Generated by Django 4.0 on 2024-01-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_items_qty_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdish',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
