# Generated by Django 4.0 on 2024-02-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_dishcategory_dish'),
        ('shop', '0006_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderdishes', to='catalog.dish', verbose_name='Товары в заказе'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderdishes', to='shop.order', verbose_name='Заказ'),
        ),
    ]
