# Generated by Django 4.0 on 2024-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_discount_order_manual_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='takeaway_disc_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рассчитывается автоматически.', max_digits=8, null=True, verbose_name='скидка самовывоз, DIN'),
        ),
    ]
