# Generated by Django 4.0 on 2024-01-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cartdish_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdish',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
