# Generated by Django 4.0 on 2023-12-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_promonews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoNews',
        ),
    ]
