# Generated by Django 4.0 on 2024-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orderdish_dish_alter_orderdish_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card')], default='cash', max_length=20, verbose_name='способ оплаты'),
            preserve_default=False,
        ),
    ]
