# Generated by Django 4.0 on 2024-04-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_takeaway_disc_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address_data',
        ),
        migrations.AddField(
            model_name='order',
            name='address_comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Данные адреса'),
        ),
        migrations.AddField(
            model_name='order',
            name='coordinates',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='координаты'),
        ),
    ]
