# Generated by Django 4.0 on 2024-02-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0006_remove_restaurant_work_hours_restaurant_close_time_and_more'),
        ('shop', '0008_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='заказы', to='delivery_contacts.restaurant', verbose_name='точка'),
        ),
    ]
