# Generated by Django 4.0 on 2023-12-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_delivery_alter_order_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='unit_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.CharField(default=0, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items_num',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Кол-во'),
        ),
    ]
