# Generated by Django 4.0 on 2024-04-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_order_delivery_address_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рассчитывается автоматически.', max_digits=8, null=True, verbose_name='скидка за оплату наличными, DIN'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[(1, 'first_order'), (2, 'cash_on_delivery')], max_length=20, unique=True, verbose_name='тип скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('card_on_delivery', 'card_on_delivery'), ('card', 'card')], max_length=20, verbose_name='способ оплаты *'),
        ),
    ]
