# Generated by Django 4.0 on 2023-12-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_amount_alter_orderdish_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='amount',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
