# Generated by Django 4.0 on 2024-02-29 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0007_alter_delivery_discount_alter_deliveryzone_is_promo_and_more'),
        ('catalog', '0007_alter_dish_article_alter_dish_final_price_and_more'),
        ('users', '0005_alter_baseprofile_date_of_birth'),
        ('shop', '0009_alter_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdish',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Посчитается автоматически.', max_digits=7, verbose_name='Стоимость всей позиции, DIN.'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='base_profile',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Подтянется автоматически.', null=True, verbose_name='Запись baseprofile в БД'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='cart_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Подтянется автоматически.', null=True, verbose_name='Запись корзины в БД'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='dish',
            field=models.ForeignKey(help_text='Начните писать название блюда...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartdishes', to='catalog.dish', verbose_name='Товары в корзине *'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='dish_article',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Подтянется автоматически.', null=True, verbose_name='Запись блюда в БД'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Внесите колличество.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во *'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Подтянется автоматически.', max_digits=6, null=True, verbose_name='Цена за ед-цу, DIN.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Посчитается автоматически.', max_digits=8, verbose_name='сумма заказа до скидки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('Novi_sad', 'Novi Sad')], max_length=20, verbose_name='город *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_contacts.delivery', verbose_name='доставка *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Посчитается автоматически. Для доставки будет +, для самовывоза -.', max_digits=7, null=True, verbose_name='стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Опциональная доп скидка вводится вручную в формате '0000.00'.", max_digits=8, null=True, verbose_name='Доп скидка, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Посчитается автоматически.', max_digits=8, verbose_name='Сумма заказа после скидок, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount_with_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Посчитается автоматически.', max_digits=8, verbose_name='Сумма заказа с учетом скидок и доставки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_qty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Посчитается автоматически.', verbose_name='Кол-во ед-ц заказа, шт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(blank=True, help_text='Проставится автоматически.', null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card')], max_length=20, verbose_name='способ оплаты *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='persons_qty',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Кол-во приборов *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(max_length=400, validators=[users.validators.validate_first_and_last_name], verbose_name='имя получателя *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79151013419', help_text="Внесите телефон, прим. '+38212345678'. Для пустого значения, внесите 'None'.", max_length=128, region=None, verbose_name='телефон получателя *'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Подтянется автоматически.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='заказы', to='delivery_contacts.restaurant', verbose_name='точка '),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Поиск по имени и номеру телефона.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.baseprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Посчитается автоматически.', max_digits=10, verbose_name='Сумма, DIN'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Посчитается автоматически.', max_digits=10, verbose_name='Итог сумма, DIN'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items_qty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Посчитается автоматически.', verbose_name='Кол-во порций, шт'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Поиск в поле по имени и номеру телефона.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.baseprofile', verbose_name='ID клиента'),
        ),
    ]
