# Generated by Django 4.0 on 2024-04-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_cash_discount_alter_discount_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cash_discount',
            new_name='cash_discount_amount',
        ),
    ]
