# Generated by Django 4.0 on 2023-12-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
        ('shop', '0010_alter_order_amount_alter_orderdish_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdish',
            options={'ordering': ['cart'], 'verbose_name': 'связь корзина-блюдо', 'verbose_name_plural': 'связи корзина-блюдо'},
        ),
        migrations.AddField(
            model_name='cartdish',
            name='amount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='скидка'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='final_amount',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Итог сумма'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='complited',
            field=models.BooleanField(default=False, verbose_name='Заказана'),
        ),
    ]
