# Generated by Django 4.0 on 2024-03-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_cartdish_amount_alter_cartdish_base_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr-latn', 'Serbian')], default='sr-latn', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Уточнение по адресу доставки: частный дом / этаж, квартира, домофон. Прочие комм к заказу', max_length=400, null=True, verbose_name='Комментарий'),
        ),
    ]
