# Generated by Django 4.0 on 2023-12-22 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_dish_discount_alter_dish_price'),
        ('shop', '0011_alter_cartdish_options_cartdish_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdish',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='dishes',
            field=models.ManyToManyField(blank=True, help_text='Добавьте блюда в заказ.', null=True, through='shop.CartDish', to='catalog.Dish', verbose_name='Товары в заказе'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Итог сумма'),
        ),
    ]
