# Generated by Django 4.0 on 2024-03-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_language_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.JSONField(blank=True, default=dict, help_text='для хранения адреса и координат доставки', null=True, verbose_name='Данные доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('sr-latn', 'Serbian')], help_text='Язык общения.', max_length=10, null=True, verbose_name='lg'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='base_profile',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ID baseprofile/БД'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='dish_article',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Арт. блюда/БД'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='# заказа/БД'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Сумма скидки по промокоду, DIN'),
        ),
    ]
