# Generated by Django 4.0 on 2024-04-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0009_alter_deliveryzone_polygon'),
        ('shop', '0011_alter_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_comment',
            field=models.CharField(blank=True, default='flat: , floor: , interfon: ', max_length=50, null=True, verbose_name='Данные адреса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_contacts.delivery', verbose_name='доставка *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('card_on_delivery', 'card_on_delivery'), ('card', 'card')], default='card_on_delivery', max_length=20, verbose_name='способ оплаты *'),
        ),
    ]
