# Generated by Django 4.0 on 2023-12-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_dish_discount_alter_dish_price'),
        ('shop', '0012_alter_cartdish_amount_alter_cartdish_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items_num',
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_dishes', to='shop.shoppingcart', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Сумма, DIN'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Скидка, DIN'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='dishes',
            field=models.ManyToManyField(help_text='Добавьте блюда в заказ.', through='shop.CartDish', to='catalog.Dish', verbose_name='Товары в заказе'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Итог сумма, DIN'),
        ),
    ]
