# Generated by Django 4.0 on 2024-03-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_delivery_address_alter_order_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='delivery_address_data',
        ),
    ]
