# Generated by Django 4.0 on 2024-04-30 10:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_dish_article'),
        ('shop', '0012_alter_order_address_comment_alter_order_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_comment',
            field=models.CharField(blank=True, default='flat: , floor: , interfon: ', help_text='flat: , floor: , interfon: ', max_length=50, null=True, verbose_name='Данные адреса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('sr-latn', 'Serbian')], default='sr-latn', help_text='Язык общения.', max_length=10, null=True, verbose_name='lg'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WCO', 'ожидает подтверждения'), ('CFD', 'подтвержден'), ('OND', 'передан в доставку'), ('CND', 'отменен')], default='WCO', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='dish',
            field=models.ForeignKey(help_text='Перед удалением поставьте кол-во 0 для обнуления ИТОГО.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderdishes', to='catalog.dish', verbose_name='Товары в заказе'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Перед удалением поставьте кол-во 0 для обнуления ИТОГО.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во'),
        ),
    ]
