# Generated by Django 4.0 on 2024-01-04 16:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
        ('catalog', '0012_rename_spicy_dish_spicy_icon_and_more'),
        ('users', '0006_alter_webaccount_phone'),
        ('shop', '0013_remove_shoppingcart_items_num_alter_cartdish_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='session_id',
            new_name='device_id',
        ),
        migrations.AddField(
            model_name='order',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Скидка, DIN'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Итог сумма, DIN'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.baseprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dishes', to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='dishes',
            field=models.ManyToManyField(help_text='Добавьте блюда в корзину.', through='shop.CartDish', to='catalog.Dish', verbose_name='Товары в корзине'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.baseprofile', verbose_name='Клиент'),
        ),
    ]
