# Generated by Django 4.0 on 2024-05-17 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0005_messengeraccount_msngr_first_name_and_more'),
        ('shop', '0013_alter_order_address_comment_alter_order_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.BooleanField(default=True, verbose_name='чек'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='оплачен'),
        ),
        migrations.AddField(
            model_name='order',
            name='msngr_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tm_bot.messengeraccount', verbose_name='Аккаунт в соц сетях'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('P1', 'Glovo'), ('P2', 'Wolt'), ('1', 'телефон'), ('2', 'ресторан'), ('3', 'TM_Bot'), ('4', 'сайт')], default='web_page', max_length=20, verbose_name='источник заказа *'),
        ),
        migrations.AddField(
            model_name='order',
            name='source_id',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'admin')], help_text='ID заказа в системе-источнике.', null=True, verbose_name='ID источника'),
        ),
        migrations.AlterField(
            model_name='order',
            name='persons_qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Кол-во приборов *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(help_text="Внесите телефон, прим. '+38212345678'.", max_length=128, verbose_name='телефон получателя *'),
        ),
    ]
