# Generated by Django 4.0 on 2024-03-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_delivery_address_order_delivery_address_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdish',
            name='base_profile',
        ),
        migrations.RemoveField(
            model_name='orderdish',
            name='base_profile',
        ),
    ]
