# Generated by Django 4.0 on 2024-05-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_invoice_order_is_paid_order_msngr_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('P1-1', 'Glovo'), ('P1-2', 'Wolt'), ('1', 'телефон'), ('2', 'ресторан'), ('3', 'TM_Bot'), ('4', 'сайт')], default='web_page', max_length=20, verbose_name='источник заказа *'),
        ),
    ]
