# Generated by Django 4.0 on 2024-01-08 17:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_webaccount_phone'),
        ('delivery_contacts', '0003_districtdeliverycost'),
        ('shop', '0014_rename_session_id_shoppingcart_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Сумма заказа после скидок, DIN'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount_with_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='delivery_contacts.districtdeliverycost', verbose_name='Район'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма, DIN'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID устройства'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Итог сумма, DIN'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.baseprofile', verbose_name='ID клиента'),
        ),
    ]
