# Generated by Django 4.0 on 2024-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_cartdish_base_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_first_order',
            field=models.BooleanField(default=False, verbose_name='Первый заказ'),
        ),
    ]
