# Generated by Django 4.0 on 2024-05-19 07:11

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('P1-1', 'Glovo'), ('P1-2', 'Wolt'), ('1', 'телефон'), ('2', 'ресторан'), ('3', 'TM_Bot'), ('4', 'сайт')], default='4', max_length=20, verbose_name='источник заказа *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=400, null=True, validators=[users.validators.validate_first_and_last_name], verbose_name='имя получателя *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text="Внесите телефон, прим. '+38212345678'.", max_length=128, null=True, verbose_name='телефон получателя *'),
        ),
    ]
