# Generated by Django 4.0 on 2024-03-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_is_first_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='delivery_time',
        ),
    ]
