# Generated by Django 4.0 on 2024-01-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0003_districtdeliverycost'),
        ('shop', '0015_remove_order_final_amount_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='сумма заказа до скидки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount_with_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='Сумма заказа с учетом скидок и доставки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery_contacts.districtdeliverycost', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(default='+79151013419', max_length=100, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='время доставки'),
        ),
    ]
