# Generated by Django 4.0 on 2024-03-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_time_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('Novi_sad', 'Novi Sad')], default='Beograd', max_length=20, verbose_name='город *'),
        ),
    ]
