# Generated by Django 4.0 on 2024-03-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0009_alter_deliveryzone_polygon'),
        ('shop', '0017_alter_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=1, help_text='Подтянется автоматически.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='заказы', to='delivery_contacts.restaurant', verbose_name='точка '),
        ),
    ]
