# Generated by Django 4.0 on 2024-05-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_source_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='origin',
            new_name='source',
        ),
    ]
