# Generated by Django 4.0 on 2024-03-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_webaccount_notes'),
        ('shop', '0018_alter_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Поиск в поле по имени и номеру телефона.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.baseprofile', verbose_name='ID клиента'),
        ),
    ]
