# Generated by Django 4.0 on 2024-05-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0010_courier'),
        ('shop', '0018_rename_origin_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_contacts.courier', verbose_name='Курьер'),
        ),
    ]
