# Generated by Django 4.0 on 2024-05-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_orderglovoproxy_orderwoltproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderglovoproxy',
            options={'verbose_name': 'заказ Glovo', 'verbose_name_plural': 'заказы Glovo'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('card_on_delivery', 'card_on_delivery'), ('card', 'card'), ('partner', 'partner')], default='card_on_delivery', max_length=20, verbose_name='способ оплаты *'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='unit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
