# Generated by Django 4.0 on 2024-05-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_orderglovoproxy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderwoltproxy',
            options={'verbose_name': 'заказ Wolt', 'verbose_name_plural': 'заказы Wolt'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('1', 'first_order'), ('2', 'cash_on_delivery'), ('3', 'instagram_story'), ('4', 'birthday')], max_length=20, unique=True, verbose_name='тип скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('card_on_delivery', 'card_on_delivery'), ('partner', 'partner')], max_length=20, null=True, verbose_name='способ оплаты *'),
        ),
    ]
