# Generated by Django 4.0 on 2024-05-27 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_orderwoltproxy_options_alter_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auth_fst_ord_disc',
            field=models.BooleanField(default=False, verbose_name='скидка за первый заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_discount_disc',
            field=models.BooleanField(default=False, verbose_name='скидка за оплату наличными'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.discount', verbose_name='скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='takeaway_disc',
            field=models.BooleanField(default=False, verbose_name='скидка самовывоз'),
        ),
    ]
