# Generated by Django 4.0 on 2024-05-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_order_discount_amount_alter_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='имя получателя *'),
        ),
    ]
