# Generated by Django 4.0 on 2024-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_order_recipient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[(1, 'first_order'), (2, 'takeaway'), (3, 'cash_on_delivery'), (4, 'instagram_story'), (5, 'birthday')], max_length=20, unique=True, verbose_name='тип скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd')], default='Beograd', max_length=20, verbose_name='город *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('card_on_delivery', 'card_on_delivery'), ('card', 'card'), ('partner', 'partner')], max_length=20, null=True, verbose_name='способ оплаты *'),
        ),
    ]
