# Generated by Django 4.0 on 2024-06-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_discount_type_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='process_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ошибки сохранения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manual_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Опциональная доп скидка вводится вручную в формате '0000.00'.<br>Добавится к скидке/промокоду.", max_digits=8, null=True, verbose_name='Доп скидка, DIN'),
        ),
    ]
