# Generated by Django 4.0 on 2024-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_order_process_comment_alter_order_manual_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process_comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ошибки сохранения'),
        ),
    ]
