# Generated by Django 4.0 on 2024-06-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_order_process_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='auth_fst_ord_disc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='auth_fst_ord_disc_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cash_discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cash_discount_disc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='takeaway_disc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='takeaway_disc_amount',
        ),
    ]
