# Generated by Django 4.0 on 2024-06-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_order_auth_fst_ord_disc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSmokeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'заказ Smoke',
                'verbose_name_plural': 'заказы Smoke',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
    ]
