# Generated by Django 4.0 on 2024-06-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_ordersmokeproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_with_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Посчитается автоматически.', max_digits=8, verbose_name='Сумма заказа с учетом доставки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_comment',
            field=models.CharField(blank=True, default='flat: , floor: , interfon: ', help_text='flat: #####, floor: #####, interfon: ##########', max_length=50, null=True, verbose_name='Данные адреса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('P1-1', 'Glovo'), ('P1-2', 'Wolt'), ('P2-1', 'Smoke'), ('1', 'телефон'), ('2', 'ресторан'), ('3', 'TM_Bot'), ('4', 'сайт')], default='4', max_length=20, verbose_name='источник заказа *'),
        ),
    ]
