# Generated by Django 4.0 on 2024-06-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_order_amount_with_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_comment',
            field=models.CharField(blank=True, default='flat: , floor: , interfon: ', help_text='flat: #####, floor: #####, interfon: ##########', max_length=177, null=True, verbose_name='Данные адреса'),
        ),
    ]
