# Generated by Django 4.0 on 2024-06-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_order_address_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_comment',
            field=models.CharField(blank=True, default='flat: , floor: , interfon: ', help_text='flat: #####, floor: #####, interfon: ##########', max_length=400, null=True, verbose_name='Данные адреса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Уточнение по адресу доставки: частный дом / этаж, квартира, домофон. Прочие комм к заказу', max_length=1500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='координаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='process_comment',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='ошибки сохранения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='адрес доставки'),
        ),
    ]
