# Generated by Django 4.0 on 2024-06-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_order_address_comment_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WCO', 'ожидает подтверждения'), ('CFD', 'подтвержден'), ('OND', 'передан в доставку'), ('CND', 'отменен'), ('DLD', 'выдан')], default='WCO', max_length=3, verbose_name='Статус'),
        ),
    ]
