# Generated by Django 4.0 on 2024-06-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_tm_msg_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер сообщения в админском чате'),
        ),
    ]
