# Generated by Django 4.0 on 2024-07-01 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0008_alter_messengeraccount_options_and_more'),
        ('shop', '0036_order_admin_tm_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='msngr_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tm_bot.messengeraccount', verbose_name='Аккаунт в соц сетях'),
        ),
        migrations.AlterField(
            model_name='order',
            name='persons_qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во приборов *'),
        ),
    ]
