# Generated by Django 4.0 on 2024-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_order_msngr_account_alter_order_persons_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source_id',
            field=models.CharField(blank=True, help_text='ID заказа в системе-источнике (Bot/Wolt/Glovo/Smoke).', max_length=20, null=True, verbose_name='ID источника'),
        ),
    ]
