# Generated by Django 4.0 on 2024-09-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_order_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'permissions': [('can_add_order_1', 'Can add order to restaurant 1'), ('can_change_order_1', 'Can change order in restaurant 1'), ('can_delete_order_1', 'Can delete order from restaurant 1'), ('can_view_order_1', 'Can view order in restaurant 1'), ('can_add_order_2', 'Can add order to restaurant 2'), ('can_change_order_2', 'Can change order in restaurant 2'), ('can_delete_order_2', 'Can delete order from restaurant 2'), ('can_view_order_2', 'Can view order in restaurant 2')], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
