# Generated by Django 4.0 on 2024-09-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
