# Generated by Django 4.0 on 2024-09-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'permissions': [('can_create_order_rest_1', 'Can create order rest 1'), ('can_change_order_rest_1', 'Can change order rest 1'), ('can_delete_order_rest_1', 'Can delete order rest 1'), ('can_create_order_rest_2', 'Can create order rest 2'), ('can_change_order_rest_2', 'Can change order rest 2'), ('can_delete_order_rest_2', 'Can delete order rest 2')], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
