# Generated by Django 4.0 on 2024-09-19 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0015_alter_ordersbot_frontend_link_alter_ordersbot_link'),
        ('shop', '0042_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tm_bot.ordersbot', verbose_name='Бот д/заказов'),
        ),
    ]
