# Generated by Django 4.0 on 2025-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_order_orders_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNeTaDverProxy',
            fields=[
            ],
            options={
                'verbose_name': 'заказ Не та дверь',
                'verbose_name_plural': 'заказы Не та дверь',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('P1-1', 'Glovo'), ('P1-2', 'Wolt'), ('P2-1', 'Smoke'), ('P2-2', 'Не та дверь'), ('1', 'телефон'), ('2', 'ресторан'), ('3', 'TM_Bot'), ('4', 'сайт')], default='4', max_length=20, verbose_name='источник заказа *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WCO', 'ожидает подтверждения'), ('CFD', 'подтвержден'), ('DLD', 'выдан'), ('CND', 'отменен')], default='WCO', max_length=3, verbose_name='Статус'),
        ),
    ]
