# Generated by Django 4.0 on 2025-02-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_ordernetadverproxy_alter_order_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSealTeaProxy',
            fields=[
            ],
            options={
                'verbose_name': 'заказ Seal Tea',
                'verbose_name_plural': 'заказы Seal Tea',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время выдачи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('P1-1', 'Glovo'), ('P1-2', 'Wolt'), ('P2-1', 'Smoke'), ('P2-2', 'Не та дверь'), ('P3-1', 'Seal Tea'), ('1', 'телефон'), ('2', 'ресторан'), ('3', 'TM_Bot'), ('4', 'сайт')], default='4', max_length=20, verbose_name='источник заказа *'),
        ),
    ]
