# Generated by Django 4.0 on 2025-02-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_ordersealteaproxy_alter_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('cash', 'cash'), ('card_on_delivery', 'card_on_delivery'), ('card', 'card'), ('partner', 'partner')], max_length=20, null=True, verbose_name='способ оплаты *'),
        ),
    ]
