# Generated by Django 4.0 on 2025-02-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='рассчитывается автоматически.', max_digits=8, null=True, verbose_name='размер скидки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('card_on_delivery', 'card_on_delivery'), ('card', 'card'), ('partner', 'partner')], max_length=20, null=True, verbose_name='способ оплаты *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promocode_disc_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='рассчитывается автоматически.', max_digits=8, null=True, verbose_name='скидка по промокоду, DIN'),
        ),
    ]
