# Generated by Django 4.0 on 2025-02-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_alter_order_discount_amount_alter_order_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[(None, '-------'), ('cash', 'cash'), ('card_on_delivery', 'card_on_delivery'), ('card', 'card'), ('partner', 'partner')], max_length=20, null=True, verbose_name='способ оплаты *'),
        ),
    ]
