# Generated by Django 4.0 on 2025-03-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[(None, '-------'), ('cash', 'cash'), ('card_on_delivery', 'card_on_delivery'), ('card', 'card')], max_length=20, null=True, verbose_name='способ оплаты *'),
        ),
    ]
