# Generated by Django 4.0 on 2025-03-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WCO', 'ожидает подтверждения'), ('CFD', 'подтвержден'), ('OND', 'отправлен'), ('CND', 'отменен')], default='WCO', max_length=3, verbose_name='Статус'),
        ),
    ]
