# Generated by Django 4.0 on 2025-03-04 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Перед удалением поставьте кол-во 0 для обнуления ИТОГО.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во'),
        ),
    ]
