# Generated by Django 4.0 on 2025-03-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WCO', 'ожидает подтверждения'), ('CFD', 'подтвержден'), ('RDY', 'готов'), ('OND', 'отправлен'), ('CND', 'отменен')], default='WCO', max_length=3, verbose_name='Статус'),
        ),
    ]
