# Generated by Django 4.0 on 2025-03-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0025_rename_min_сourier_payout_courier_min_payout'),
        ('shop', '0054_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[(1, 'first_order'), (2, 'takeaway'), (3, 'cash_on_delivery'), (4, 'instagram_story'), (5, 'birthday'), (6, 'for insiders')], max_length=20, unique=True, verbose_name='тип скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_contacts.delivery', verbose_name='доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[(None, '-------'), ('cash', 'cash'), ('card_on_delivery', 'bezgotovinsko'), ('card', 'card')], max_length=20, null=True, verbose_name='способ оплаты *'),
        ),
    ]
