# Generated by Django 4.0 on 2025-03-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_alter_discount_type_alter_order_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.IntegerField(choices=[(1, 'first_order'), (2, 'takeaway'), (3, 'cash_on_delivery'), (4, 'instagram_story'), (5, 'birthday'), (6, 'for insiders')], max_length=20, unique=True, verbose_name='тип скидки'),
        ),
    ]
