# Generated by Django 4.0 on 2025-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_alter_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manual_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Доп скидка вводится вручную прим.'0000.00'.<br>Для внесения отмените другие скидки.", max_digits=8, null=True, verbose_name='Доп скидка, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text="Внесите телефон, прим. '+38212345678'.", max_length=128, null=True, verbose_name='телефон получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_id',
            field=models.CharField(blank=True, help_text='ID заказа в системе-источнике<br>(TmBot/Wolt/Glovo/Smoke/NeTa/SealTea).', max_length=20, null=True, verbose_name='ID источника'),
        ),
    ]
