# Generated by Django 4.0 on 2025-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_order_manual_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manual_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Доп скидка вводится вручную прим.'10.00'.<br>", max_digits=8, null=True, verbose_name='Доп скидка, %'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('P1-1', 'Glovo'), ('P1-2', 'Wolt'), ('P2-1', 'Smoke'), ('P2-2', 'Не та дверь'), ('P3-1', 'Seal Tea'), ('1', 'внутренний'), ('3', 'TM_Bot'), ('4', 'сайт')], default='4', max_length=20, verbose_name='источник заказа *'),
        ),
    ]
