# Generated by Django 4.0 on 2025-03-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_alter_order_manual_discount_alter_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='стоимость доставки'),
        ),
    ]
