# Generated by Django 4.0 on 2025-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_alter_order_delivery_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-execution_date', '-order_number'], 'permissions': [('can_create_order_rest_1', 'Can create order rest 1'), ('can_change_order_rest_1', 'Can change order rest 1'), ('can_delete_order_rest_1', 'Can delete order rest 1'), ('can_create_order_rest_2', 'Can create order rest 2'), ('can_change_order_rest_2', 'Can change order rest 2'), ('can_delete_order_rest_2', 'Can delete order rest 2')], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order_number_created',
        ),
        migrations.AddField(
            model_name='order',
            name='execution_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_number', 'execution_date'), name='unique_order_number_created'),
        ),
    ]
