# Generated by Django 4.0 on 2025-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_remove_order_unique_order_number_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manual_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Доп скидка вводится вручную прим.'10.00'.<br>", max_digits=8, null=True, verbose_name='Доп скидка, DIN'),
        ),
    ]
