# Generated by Django 4.0 on 2025-11-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0010_campaign_alter_promobroadcast_body_campaignopenevent'),
        ('shop', '0064_alter_order_persons_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='promos.campaign', verbose_name='Рекл. кампания'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='cart_number',
            field=models.PositiveIntegerField(blank=True, help_text='Подтянется автоматически.', null=True, verbose_name='Запись корзины в БД'),
        ),
        migrations.AlterField(
            model_name='cartdish',
            name='dish_article',
            field=models.PositiveIntegerField(blank=True, help_text='Подтянется автоматически.', null=True, verbose_name='Запись блюда в БД'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='dish_article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Арт. блюда/БД'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='# заказа/БД'),
        ),
    ]
