# Generated by Django 4.0 on 2026-02-12 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_order_campaign_alter_cartdish_cart_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='persons_qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Кол-во приборов *'),
        ),
    ]
