# Generated by Django 4.0 on 2026-04-01 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_alter_order_persons_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='persons_qty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Кол-во приборов *'),
        ),
    ]
