# Generated by Django 4.0 on 2026-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_alter_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('P1-1', 'Glovo'), ('P1-2', 'Wolt'), ('P2-1', 'Smoke'), ('P2-2', 'Не та дверь'), ('P3-1', 'Seal Tea'), ('1', 'внутренний'), ('3', 'TM_Bot'), ('4', 'сайт')], default='4', max_length=20, verbose_name='источник заказа *'),
        ),
    ]
