# Generated by Django 4.0 on 2026-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_alter_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdish',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Стоимость всей позиции, DIN.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='сумма заказа до скидки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_with_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Сумма заказа с учетом доставки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Сумма заказа после скидок, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount_with_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Сумма заказа с учетом скидок и доставки, DIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_qty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Кол-во ед-ц заказа, шт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text="Внесите телефон, прим. '+38212345678'.", max_length=128, null=True, verbose_name='☎'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма, DIN'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Итог сумма, DIN'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items_qty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Кол-во порций, шт'),
        ),
    ]
