# Generated by Django 4.0 on 2023-12-04 15:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок отображения в меню')),
                ('name_rus', models.CharField(max_length=200, unique=True, verbose_name='Название RUS')),
                ('name_srb', models.CharField(max_length=200, unique=True, verbose_name='Название SRB')),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(help_text='Укажите уникальный адрес для категории блюд. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', max_length=200, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(validators=[django.core.validators.MinValueValidator(6)], verbose_name='артикул')),
                ('active', models.BooleanField(default=False, verbose_name='активен')),
                ('short_name_rus', models.CharField(db_index=True, help_text='Добавьте название блюда.', max_length=200, verbose_name='Название РУС')),
                ('short_name_srb', models.CharField(db_index=True, help_text='Добавьте название блюда.', max_length=200, verbose_name='Название SRB')),
                ('text_rus', models.CharField(help_text='Добавьте описание блюда.', max_length=200, verbose_name='Описание РУС')),
                ('text_srb', models.CharField(help_text='Добавьте описание блюда.', max_length=200, verbose_name='Описание SRB')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='цена')),
                ('weight', models.CharField(help_text='Добавьте вес в гр.', max_length=10, verbose_name='вес, гр')),
                ('uom', models.CharField(help_text='Добавьте единицы измерения.', max_length=10, verbose_name='ед-ца измерения')),
                ('volume', models.CharField(help_text='Добавьте объем в единице позиции. Прим, 4 шт.', max_length=10, verbose_name='объем в ед-це поз')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(help_text='Добавьте категорию блюда.', on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
                'ordering': ['article'],
            },
        ),
    ]
