# Generated by Django 4.0 on 2023-12-21 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_dish_article_alter_dish_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.dish', verbose_name='блюдо'),
        ),
    ]
