# Generated by Django 4.0 on 2023-12-21 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_dish_category_alter_dishcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(help_text='Выберите категории блюда.', through='catalog.DishCategory', to='catalog.Category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.dish', verbose_name='блюдо'),
        ),
    ]
