# Generated by Django 4.0 on 2023-12-26 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_dish_discount_alter_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок отображения в меню'),
        ),
    ]
