# Generated by Django 4.0 on 2024-01-12 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_rename_add_date_dish_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ п/п'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='menu/dish_images/', verbose_name='Изображение'),
        ),
    ]
