# Generated by Django 4.0 on 2024-02-09 11:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msngr_type', models.CharField(choices=[('tm', 'Telegram'), ('wts', 'WhatsApp'), ('vb', 'Viber')], max_length=3, verbose_name='Тип мессенджера')),
                ('msngr_id', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='ID')),
                ('tm_chat_id', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Tm_chat_ID')),
                ('msngr_username', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Username')),
                ('msngr_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Внесите телефон, прим. '+38212345678'. Для пустого значения, внесите 'None'.", max_length=128, null=True, region=None, unique=True, verbose_name='телефон')),
                ('subscription', models.BooleanField(default=True, verbose_name='subsription')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr-latn', 'Serbian')], default='RUS', max_length=10, verbose_name='язык')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('notes', models.CharField(blank=True, max_length=400, null=True, verbose_name='Комментарии')),
                ('msngr_link', models.URLField(blank=True, null=True, verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Соц сети аккаунт',
                'verbose_name_plural': 'Соц сети аккаунты',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tm_bot.messengeraccount', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
