# Generated by Django 4.0 on 2023-12-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramaccount',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Telegram аккаунт', 'verbose_name_plural': 'Telegram аккаунты'},
        ),
        migrations.RenameField(
            model_name='telegramaccount',
            old_name='add_date',
            new_name='date_joined',
        ),
    ]
