# Generated by Django 4.0 on 2024-01-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengeraccount',
            name='msngr_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='messengeraccount',
            name='msngr_type',
            field=models.CharField(choices=[('tm', 'Telegram'), ('wts', 'WhatsApp'), ('vb', 'Viber')], max_length=3, verbose_name='Тип мессенджера'),
        ),
    ]
