# Generated by Django 4.0 on 2024-01-29 10:23

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0002_messengeraccount_msngr_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengeraccount',
            name='msngr_phone',
        ),
        migrations.AddField(
            model_name='messengeraccount',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Внесите телефон, прим. '+38212345678'. Для пустого значения, внесите 'None'.", max_length=128, null=True, region=None, unique=True, verbose_name='телефон'),
        ),
    ]
