# Generated by Django 4.0 on 2024-01-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0003_remove_messengeraccount_msngr_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messengeraccount',
            old_name='phone',
            new_name='msngr_phone',
        ),
    ]
