# Generated by Django 4.0 on 2024-05-17 11:20

from django.db import migrations, models
import phonenumber_field.modelfields
import tm_bot.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0004_alter_messengeraccount_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengeraccount',
            name='msngr_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='messengeraccount',
            name='msngr_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='messengeraccount',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Регистрация на сайте'),
        ),
        migrations.AlterField(
            model_name='messengeraccount',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr-latn', 'Serbian')], default='sr-latn', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='messengeraccount',
            name='msngr_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Внесите телефон, прим. '+38212345678'. Для пустого значения, внесите 'None'.", max_length=128, null=True, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='messengeraccount',
            name='msngr_username',
            field=models.CharField(help_text="Для Tm username начинается с @. ( прим '@yume_sushi')<br>Для Wts username = номер телефона. (прим '+38212345678')<br>Для Vbr username = номер телефона. (прим '+38212345678')", max_length=100, unique=True, validators=[tm_bot.validators.validate_msngr_username], verbose_name='Username  *'),
        ),
        migrations.AlterField(
            model_name='messengeraccount',
            name='subscription',
            field=models.BooleanField(default=True, verbose_name='Подписка на рассылки'),
        ),
    ]
