# Generated by Django 4.0 on 2024-05-30 13:25

import django.core.validators
from django.db import migrations, models
import tm_bot.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0005_messengeraccount_msngr_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeraccount',
            name='msngr_id',
            field=models.CharField(blank=True, help_text='Только для Tm, внесется автоматически.', max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messengeraccount',
            name='msngr_username',
            field=models.CharField(help_text="Для Tm username начинается с @. ( прим '@yume_sushi')<br>Для Wts username = номер телефона. (прим '+38212345678')<br>Для Vbr username = номер телефона. (прим '+38212345678')", max_length=100, validators=[tm_bot.validators.validate_msngr_username], verbose_name='Username  *'),
        ),
    ]
