# Generated by Django 4.0 on 2024-06-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0007_alter_messengeraccount_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messengeraccount',
            options={'ordering': ['-created'], 'verbose_name': 'Соц сети аккаунт', 'verbose_name_plural': 'Соц сети аккаунты'},
        ),
        migrations.RenameField(
            model_name='messengeraccount',
            old_name='date_joined',
            new_name='created',
        ),
    ]
