# Generated by Django 4.0 on 2024-08-28 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0008_alter_messengeraccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msngr_type', models.CharField(choices=[('tm', 'Telegram'), ('wts', 'WhatsApp'), ('vb', 'Viber')], max_length=3, verbose_name='msngr typ')),
                ('msngr_id', models.CharField(blank=True, help_text='Получить через BotFather.', max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='ID бота в ТМ')),
                ('source_id', models.CharField(blank=True, help_text='ID бота на платформе ботов.', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='ID на платформе')),
                ('city', models.CharField(blank=True, choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], default='Beograd', max_length=40, null=True, verbose_name='город *')),
            ],
        ),
        migrations.AddField(
            model_name='messengeraccount',
            name='city',
            field=models.CharField(blank=True, choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], default='Beograd', max_length=40, null=True, verbose_name='город *'),
        ),
    ]
