# Generated by Django 4.0 on 2024-09-05 06:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0020_remove_restaurant_admin'),
        ('tm_bot', '0010_rename_bot_ordersbot_alter_ordersbot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersbot',
            name='link',
            field=models.URLField(default='https://t.me/YUME_SUSHI_bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersbot',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='adminchattm',
            name='restaurant',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_chat', to='delivery_contacts.restaurant', verbose_name='ресторан'),
        ),
        migrations.AlterField(
            model_name='ordersbot',
            name='city',
            field=models.CharField(blank=True, choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], default='Beograd', max_length=40, null=True, unique=True, verbose_name='город *'),
        ),
        migrations.AlterField(
            model_name='ordersbot',
            name='source_id',
            field=models.CharField(blank=True, help_text='ID бота на платформе ботов.', max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='ID на платформе'),
        ),
    ]
