# Generated by Django 4.0 on 2024-09-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0011_ordersbot_link_ordersbot_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersbot',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Активный чат отображается на сайте.', verbose_name='активен'),
        ),
    ]
