# Generated by Django 4.0 on 2024-09-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0012_ordersbot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersbot',
            name='api_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='API ключ д/валидации источника сообщений'),
        ),
    ]
