# Generated by Django 4.0 on 2024-09-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0013_ordersbot_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersbot',
            name='frontend_link',
            field=models.URLField(default='https://t.me/YUME_SUSHI_bot?start=78cexaiigs'),
            preserve_default=False,
        ),
    ]
