# Generated by Django 4.0 on 2024-09-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0014_ordersbot_frontend_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersbot',
            name='frontend_link',
            field=models.URLField(help_text='Сссылка для отображения на сайте. Собирает статистику по клиентам, которые перешли с сайта.'),
        ),
        migrations.AlterField(
            model_name='ordersbot',
            name='link',
            field=models.URLField(help_text='Стандартная ссылка на бота.'),
        ),
    ]
