# Generated by Django 4.0 on 2024-09-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0015_alter_ordersbot_frontend_link_alter_ordersbot_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersbot',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API ключ д/валидации источника сообщений'),
        ),
    ]
