# Generated by Django 4.0 on 2024-09-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0016_alter_ordersbot_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersbot',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API ключ д/синхронизации информации о заказах<br>изменению статуса заказа через админку)'),
        ),
        migrations.AlterField(
            model_name='ordersbot',
            name='frontend_link',
            field=models.URLField(help_text='Сссылка для отображения на сайте.<br>Собирает статистику по клиентам, которые перешли с сайта.'),
        ),
    ]
