# Generated by Django 4.0 on 2025-10-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0017_alter_ordersbot_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersbot',
            name='msngr_id',
        ),
    ]
