# Generated by Django 4.0 on 2025-11-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0018_remove_ordersbot_msngr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengeraccount',
            name='can_write',
            field=models.BooleanField(default=False, verbose_name='Бот может писать пользователю'),
        ),
    ]
