# Generated by Django 4.0 on 2025-11-11 21:58

from django.db import migrations, models
import tm_bot.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0019_messengeraccount_can_write'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messengeraccount',
            options={'ordering': ['-created'], 'verbose_name': 'Мессенджер аккаунт', 'verbose_name_plural': 'Мессенджер аккаунты'},
        ),
        migrations.AlterField(
            model_name='messengeraccount',
            name='msngr_username',
            field=models.CharField(help_text="Для Tm username в начале ничего нет<br>Для Wts username = номер телефона. (прим '+38212345678')<br>Для Vbr username = номер телефона. (прим '+38212345678')", max_length=100, validators=[tm_bot.validators.validate_msngr_username], verbose_name='Username  *'),
        ),
    ]
