# Generated by Django 4.0 on 2025-11-24 18:02

from django.db import migrations, models
import django.db.models.deletion
import tm_bot.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0020_alter_messengeraccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengeraccount',
            name='can_write',
        ),
        migrations.AlterField(
            model_name='messengeraccount',
            name='msngr_username',
            field=models.CharField(blank=True, help_text="Для Tm username в начале ничего нет<br>Для Wts username = номер телефона. (прим '+38212345678')<br>Для Vbr username = номер телефона. (прим '+38212345678')", max_length=100, null=True, validators=[tm_bot.validators.validate_msngr_username], verbose_name='Username  *'),
        ),
        migrations.CreateModel(
            name='MessengerAccountBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_can_write', models.BooleanField(blank=True, help_text='None — ещё не пробовали писать; True — была успешная отправка; False — бот заблокирован пользователем (403 bot was blocked).', null=True, verbose_name='Бот может писать этому пользователю')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя успешная отправка')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя ошибка отправки')),
                ('last_error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код последней ошибки Telegram')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='tm_bot.ordersbot', verbose_name='Бот заказов')),
                ('messenger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_links', to='tm_bot.messengeraccount', verbose_name='Telegram аккаунт')),
            ],
            options={
                'verbose_name': 'Связка аккаунт–бот',
                'verbose_name_plural': 'Связки аккаунт–бот',
                'unique_together': {('messenger_account', 'bot')},
            },
        ),
    ]
