# Generated by Django 4.0 on 2025-11-25 10:12

from django.db import migrations, models
import tm_bot.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0021_remove_messengeraccount_can_write_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeraccount',
            name='msngr_username',
            field=models.CharField(default='', help_text="Для Tm username в начале ничего нет<br>Для Wts username = номер телефона. (прим '+38212345678')<br>Для Vbr username = номер телефона. (прим '+38212345678')", max_length=100, validators=[tm_bot.validators.validate_msngr_username], verbose_name='Username  *'),
            preserve_default=False,
        ),
    ]
