# Generated by Django 4.0 on 2025-12-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0022_alter_messengeraccount_msngr_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeraccount',
            name='msngr_link',
            field=models.URLField(blank=True, help_text='Ссылка на чат создаётся автоматически.<br>Если у пользователя нет username (для Telegram) или телефона (для WhatsApp), то перейти в чат невозможно.', null=True, verbose_name='Текст ссылки в Чат'),
        ),
    ]
