# Generated by Django 4.0 on 2025-12-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0023_alter_messengeraccount_msngr_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersbot',
            name='admin_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID админа'),
        ),
        migrations.AddField(
            model_name='ordersbot',
            name='admin_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username админа'),
        ),
    ]
