# Generated by Django 4.0 on 2026-02-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0025_alter_messengeraccount_msngr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengeraccountbot',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
    ]
