# Generated by Django 4.0 on 2026-03-18 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0026_messengeraccountbot_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersbot',
            name='admin_id',
            field=models.CharField(blank=True, help_text='Кому будет отправляться тестовая промо-рассылка', max_length=100, null=True, verbose_name='ID админа'),
        ),
        migrations.AlterField(
            model_name='ordersbot',
            name='msngr_type',
            field=models.CharField(choices=[('tm', 'Telegram'), ('wts', 'WhatsApp'), ('vb', 'Viber')], max_length=3, verbose_name='Тип мессенджера'),
        ),
        migrations.AlterField(
            model_name='ordersbot',
            name='name',
            field=models.CharField(blank=True, help_text='Это внутреннее название для системы.<br>Реальное название менять через BotFather.', max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Название'),
        ),
    ]
