# Generated by Django 4.0 on 2024-04-07 22:18

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tm_bot', '0003_alter_messengeraccount_msngr_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WEBAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='name')),
                ('last_name', models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='last_name')),
                ('password', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('web_language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr-latn', 'Serbian')], default='sr-latn', max_length=10, verbose_name='Язык сайта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone')),
                ('notes', models.TextField(blank=True, max_length=400, null=True, verbose_name='Пометки')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=9, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=False, help_text='Аккаунт активирован.Пользователь перешел по ссылке из письма для активации аккаунта.', verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Был ли аккаунт удален.', verbose_name='deleted')),
                ('is_subscribed', models.BooleanField(default=True, help_text='Подписка на рассылки.', verbose_name='подписка')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'WEB account',
                'verbose_name_plural': 'WEB accounts',
            },
        ),
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Внесите телефон, прим. '+38212345678'. Для пустого значения, внесите 'None'.", max_length=128, null=True, region=None, unique=True, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='Город')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('notes', models.CharField(blank=True, max_length=400, null=True, verbose_name='Пометки')),
                ('date_of_birth', models.DateField(blank=True, help_text='Формат даты ДД.ММ.ГГГГ.', null=True, validators=[users.validators.validate_birthdate], verbose_name='День рождения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('base_language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr-latn', 'Serbian')], default='sr-latn', max_length=10, verbose_name='Язык')),
                ('orders_qty', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Считается автоматически.', verbose_name='Кол-во заказов')),
                ('messenger_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='tm_bot.messengeraccount', verbose_name='Мессенджер')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='координаты')),
                ('coordinates', models.CharField(blank=True, help_text='прим. "44.809000122132566 20.458040962192968".', max_length=60, null=True, validators=[users.validators.coordinates_validator], verbose_name='координаты ШИР (lat) ДОЛ (lon)')),
                ('comment', models.CharField(blank=True, help_text='этаж, квартира, домофон и пр информация".', max_length=400, null=True, verbose_name='доп инфо')),
                ('base_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.baseprofile', verbose_name='базовый профиль')),
            ],
            options={
                'verbose_name': 'My address',
                'verbose_name_plural': 'Мои адреса',
            },
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='my_addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='users.useraddress', verbose_name='адреса'),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='web_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_profile', to='users.webaccount', verbose_name='Аккаунт на сайте (web_account)'),
        ),
    ]
