# Generated by Django 4.0 on 2024-03-30 12:28

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webaccount',
            options={'verbose_name': 'WEB account', 'verbose_name_plural': 'WEB accounts'},
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='first_name',
            field=models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='last_name',
            field=models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone'),
        ),
    ]
