# Generated by Django 4.0 on 2024-04-08 11:11

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='comment',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='flat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='квартира'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='этаж'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='interphone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='домофон'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='coordinates',
            field=models.CharField(blank=True, help_text='прим. "44.809000122132566, 20.458040962192968".', max_length=60, null=True, validators=[users.validators.coordinates_validator], verbose_name='координаты ШИР (lat), ДОЛ (lon)'),
        ),
    ]
