# Generated by Django 4.0 on 2023-12-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddresses',
            new_name='UserAddress',
        ),
    ]
