# Generated by Django 4.0 on 2024-02-14 05:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_useraddress_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webaccount',
            name='first_name',
            field=models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='last_name',
            field=models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='Фамилия'),
        ),
    ]
