# Generated by Django 4.0 on 2024-04-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_useraddress_comment_useraddress_flat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='interphone',
            new_name='interfone',
        ),
    ]
