# Generated by Django 4.0 on 2023-12-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_useraddresses_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webaccount',
            name='email',
            field=models.EmailField(default='email@email.ru', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
