# Generated by Django 4.0 on 2024-02-14 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_webaccount_web_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webaccount',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Пароль'),
        ),
    ]
