# Generated by Django 4.0 on 2024-03-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_webaccount_options_alter_webaccount_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='first_order',
            field=models.BooleanField(default=False, verbose_name='первый заказ'),
        ),
    ]
