# Generated by Django 4.0 on 2024-04-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_interphone_useraddress_interfone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='interfone',
            new_name='interfon',
        ),
    ]
