# Generated by Django 4.0 on 2024-02-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_webaccount_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webaccount',
            name='base_profile',
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='web_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_profile', to='users.webaccount', verbose_name='Аккаунт на сайте (web_account)'),
        ),
    ]
