# Generated by Django 4.0 on 2023-12-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_webaccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='base_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baseprofile', verbose_name='базовый профиль'),
        ),
    ]
