# Generated by Django 4.0 on 2024-02-23 09:35

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_webaccount_base_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Формат даты ДД.ММ.ГГГГ.', null=True, validators=[users.validators.validate_birthdate], verbose_name='День рождения'),
        ),
    ]
