# Generated by Django 4.0 on 2024-04-30 10:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useraddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Beograd', 'Beograd'), ('Novi_sad', 'Novi Sad')], default='Beograd', max_length=20, null=True, verbose_name='город *'),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='web_account',
            field=models.OneToOneField(blank=True, help_text='Для изменения личных данных кликните на email.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_profile', to='users.webaccount', verbose_name='Аккаунт на сайте (web_account)'),
        ),
    ]
