# Generated by Django 4.0 on 2024-03-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_baseprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseprofile',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='webaccount',
            options={'verbose_name': 'Аккаунт сайта', 'verbose_name_plural': 'Аккаунты сайта'},
        ),
    ]
