# Generated by Django 4.0 on 2023-12-21 11:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useraddress_base_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webaccount',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='телефон'),
        ),
    ]
