# Generated by Django 4.0 on 2024-03-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_baseprofile_options_alter_webaccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='webaccount',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Подписка на рассылки.', verbose_name='подписка'),
        ),
    ]
