# Generated by Django 4.0 on 2024-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_baseprofile_city_alter_baseprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='orders_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Считается автоматически.', verbose_name='Сумма заказов'),
        ),
    ]
