# Generated by Django 4.0 on 2024-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_baseprofile_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Beograd', 'Beograd')], default='Beograd', max_length=20, null=True, verbose_name='город *'),
        ),
    ]
