# Generated by Django 4.0 on 2024-03-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_webaccount_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webaccount',
            name='notes',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Пометки'),
        ),
    ]
