# Generated by Django 4.0 on 2024-06-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_baseprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='flat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='квартира'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='interfon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='домофон'),
        ),
    ]
