# Generated by Django 4.0 on 2024-06-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0007_alter_messengeraccount_notes'),
        ('users', '0010_alter_baseprofile_city_alter_baseprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='messenger_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='tm_bot.messengeraccount', verbose_name='Мессенджер'),
        ),
    ]
