# Generated by Django 4.0 on 2024-03-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_useraddress_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lat',
            field=models.CharField(blank=True, help_text='прим. "POINT 44.809000122132566, 20.458040962192968".', max_length=60, null=True, verbose_name='координаты Ш,Д (lat, lon)'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lon',
            field=models.CharField(blank=True, help_text='прим. "POINT 44.809000122132566, 20.458040962192968".', max_length=60, null=True, verbose_name='координаты Ш,Д (lat, lon)'),
        ),
    ]
