# Generated by Django 4.0 on 2024-03-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_useraddress_coordinates_useraddress_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='lat',
            field=models.CharField(blank=True, help_text='прим. "44.809000122132566".', max_length=60, null=True, verbose_name='координаты ШИР (lat)'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='lon',
            field=models.CharField(blank=True, help_text='прим. "20.458040962192968".', max_length=60, null=True, verbose_name='координаты ДОЛ (lon)'),
        ),
    ]
