# Generated by Django 4.0 on 2024-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_baseprofile_first_web_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='first_web_order',
            field=models.BooleanField(default=False, verbose_name='1й зак на сайте'),
        ),
    ]
