# Generated by Django 4.0 on 2024-07-05 15:08

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_baseprofile_first_web_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(max_length=400, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='flat',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='квартира'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='floor',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='interfon',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='домофон'),
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='first_name',
            field=models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='last_name',
            field=models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='last_name'),
        ),
    ]
