# Generated by Django 4.0 on 2024-07-29 15:10

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_webaccount_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webaccount',
            name='first_name',
            field=models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='last_name',
            field=models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='last_name'),
        ),
    ]
