# Generated by Django 4.0 on 2024-08-12 15:44

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_webaccount_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webaccount',
            name='first_name',
            field=models.CharField(max_length=150, validators=[users.validators.validate_first_and_last_name], verbose_name='name'),
        ),
    ]
