# Generated by Django 4.0 on 2024-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_webaccount_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], default='Beograd', max_length=40, null=True, verbose_name='город *'),
        ),
    ]
