# Generated by Django 4.0 on 2024-08-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_baseprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Подписка на рассылки.', verbose_name='подписка'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], default='Beograd', max_length=40, null=True, verbose_name='город *'),
        ),
        migrations.AddField(
            model_name='webaccount',
            name='city',
            field=models.CharField(blank=True, choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], default='Beograd', max_length=40, null=True, verbose_name='город *'),
        ),
    ]
