# Generated by Django 4.0 on 2024-08-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_baseprofile_is_subscribed_useraddress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='is_subscribed',
        ),
    ]
