# Generated by Django 4.0 on 2024-09-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0020_remove_restaurant_admin'),
        ('users', '0021_remove_baseprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webaccount',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='delivery_contacts.restaurant', verbose_name='ресторан'),
        ),
    ]
