# Generated by Django 4.0 on 2025-09-29 22:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_webaccount_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='webaccount',
            name='auth_via',
            field=models.CharField(choices=[('email', 'Email/Password'), ('telegram', 'Telegram')], default='email', max_length=16),
        ),
        migrations.AlterField(
            model_name='webaccount',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='phone'),
        ),
    ]
