# Generated by Django 4.0 on 2024-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
