# Generated by Django 4.0 on 2024-02-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='messenger_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='мсдж_название'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='dishtranslation',
            name='msngr_short_name',
            field=models.CharField(blank=True, db_index=True, help_text='Добавьте название блюда.', max_length=200, null=True, verbose_name='мсдж_короткое описание'),
        ),
        migrations.AlterField(
            model_name='dishtranslation',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, help_text='Добавьте название блюда.', max_length=200, null=True, verbose_name='короткое описание'),
        ),
    ]
