# Generated by Django 4.0 on 2023-12-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='active',
            new_name='is_active',
        ),
    ]
