# Generated by Django 4.0 on 2024-02-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_dish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcategory',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishcategory', to='catalog.dish'),
        ),
    ]
