# Generated by Django 4.0 on 2024-02-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_categorytranslation_messenger_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytranslation',
            name='messenger_name',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='name',
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_translations', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='BotTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_translations', to='catalog.category')),
            ],
        ),
    ]
