# Generated by Django 4.0 on 2024-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_categorytranslation_messenger_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='category',
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='messenger_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='мсдж_название'),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='название'),
        ),
        migrations.DeleteModel(
            name='BotTranslation',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
