# Generated by Django 4.0 on 2024-01-25 10:26

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_categorytranslation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'category Translation'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['pk'], 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='short_name_rus',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='short_name_srb',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='text_rus',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='text_srb',
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(help_text='Выберите категории блюда.', through='catalog.DishCategory', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='catalog.dish'),
        ),
        migrations.CreateModel(
            name='DishTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('short_name', models.CharField(db_index=True, help_text='Добавьте название блюда.', max_length=200, unique=True, verbose_name='short_name')),
                ('text', models.CharField(help_text='Добавьте описание блюда.', max_length=200, verbose_name='text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.dish')),
            ],
            options={
                'verbose_name': 'dish Translation',
                'db_table': 'catalog_dish_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
