# Generated by Django 4.0 on 2023-12-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_is_active_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'связь блюдо-категория',
                'verbose_name_plural': 'связи блюдо-категория',
                'ordering': ['dish'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='скидка'),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(help_text='Выберите категории блюда.', through='catalog.DishCategory', to='catalog.Category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.dish', verbose_name='блюдо'),
        ),
        migrations.AddConstraint(
            model_name='dishcategory',
            constraint=models.UniqueConstraint(fields=('dish', 'category'), name='unique_dish_category'),
        ),
    ]
