# Generated by Django 4.0 on 2024-02-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_dishcategory_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcategory',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dishcategory', to='catalog.dish'),
        ),
    ]
