# Generated by Django 4.0 on 2023-12-21 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_dishcategory_dish_discount_remove_dish_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='article',
            field=models.CharField(help_text='Добавьте артикул прим. 0101.', max_length=6, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='discount',
            field=models.FloatField(blank=True, default=None, help_text="Внесите скидку, прим. для 10% внесите '10'.", null=True, verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Активные позиции виды пользователям.', verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(help_text='Внесите цену, DIN.', validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='short_name_rus',
            field=models.CharField(db_index=True, help_text='Добавьте название блюда RUS.', max_length=200, verbose_name='Название РУС'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='short_name_srb',
            field=models.CharField(db_index=True, help_text='Добавьте название блюда SRB.', max_length=200, verbose_name='Название SRB'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='text_rus',
            field=models.CharField(help_text='Добавьте описание блюда RUS.', max_length=200, verbose_name='Описание РУС'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='text_srb',
            field=models.CharField(help_text='Добавьте описание блюда SRB.', max_length=200, verbose_name='Описание SRB'),
        ),
    ]
