# Generated by Django 4.0 on 2024-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_dishcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dishtranslation',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, help_text='Добавьте название блюда.', max_length=200, null=True, unique=True, verbose_name='short_name'),
        ),
        migrations.AlterField(
            model_name='dishtranslation',
            name='text',
            field=models.CharField(blank=True, help_text='Добавьте описание блюда.', max_length=200, null=True, verbose_name='text'),
        ),
    ]
