# Generated by Django 4.0 on 2024-04-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_dish_article_alter_dish_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='article',
            field=models.CharField(db_index=True, help_text="Добавьте артикул, пример: '001'.\nВозможны как цифры, так и буквы.", max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='артикул *'),
        ),
    ]
