# Generated by Django 4.0 on 2023-12-22 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_dish_category_alter_dishcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text="Внесите скидку, прим. для 10% внесите '10'.", max_digits=6, null=True, verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Внесите цену, DIN.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='цена'),
        ),
    ]
