# Generated by Django 4.0 on 2024-05-23 13:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_dish_final_price_p1_alter_dish_final_price_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена после скидок в DIN. Проставится после сохранения.', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='итог цена, DIN'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='final_price_p1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Партнер P1 (GLovo/Wolt). Внесите цену в DIN. Формат 00000.00', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='цена P1, DIN *'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='final_price_p2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Партнер P2. Внесите цену в DIN. Формат 00000.00', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='цена P2, DIN *'),
        ),
    ]
