# Generated by Django 4.0 on 2023-12-27 14:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_dish_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='spicy',
            field=models.BooleanField(blank=True, default=False, help_text='иконка острое.', null=True, verbose_name='острое'),
        ),
        migrations.AddField(
            model_name='dish',
            name='vegan',
            field=models.BooleanField(blank=True, default=False, help_text='иконка веган.', null=True, verbose_name='веган'),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок отображения в меню'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Внесите цену, DIN.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок отображения в меню'),
        ),
    ]
