# Generated by Django 4.0 on 2024-01-12 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_spicy_dish_spicy_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='menu/dish_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок отображения в меню'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='short_name_rus',
            field=models.CharField(db_index=True, help_text='Добавьте название блюда RUS.', max_length=200, unique=True, verbose_name='Название РУС'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='short_name_srb',
            field=models.CharField(db_index=True, help_text='Добавьте название блюда SRB.', max_length=200, unique=True, verbose_name='Название SRB'),
        ),
    ]
