# Generated by Django 4.0 on 2024-08-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_restaurantdish_citydish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydish',
            options={'verbose_name': 'Блюдо / Город', 'verbose_name_plural': 'Блюда / Город'},
        ),
        migrations.AlterModelOptions(
            name='restaurantdish',
            options={'verbose_name': 'Блюдо / Ресторан', 'verbose_name_plural': 'Блюда / Ресторан'},
        ),
    ]
