# Generated by Django 4.0 on 2024-01-12 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_dish_image_alter_category_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['pk'], 'verbose_name': 'блюдо', 'verbose_name_plural': 'блюда'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ п/п'),
        ),
    ]
