# Generated by Django 4.0 on 2024-08-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0018_alter_delivery_max_acc_time_and_more'),
        ('catalog', '0014_rename_citydish_citydishitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ManyToManyField(to='catalog.Dish')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurantdishes', to='delivery_contacts.restaurant', verbose_name='ресторан')),
            ],
            options={
                'verbose_name': 'Блюдо / Ресторан',
                'verbose_name_plural': 'Блюда / Ресторан',
            },
        ),
        migrations.AlterUniqueTogether(
            name='restaurantdish',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='restaurantdish',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='restaurantdish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='citydishlist',
            name='name',
        ),
        migrations.AlterField(
            model_name='citydishlist',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], max_length=20, verbose_name='город'),
        ),
        migrations.DeleteModel(
            name='CityDishItem',
        ),
        migrations.DeleteModel(
            name='RestaurantDish',
        ),
    ]
