# Generated by Django 4.0 on 2024-09-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_restaurantdishlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Активные позиции отображаются на сайте.', verbose_name='активен'),
        ),
    ]
