# Generated by Django 4.0 on 2026-02-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_dish_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='includes_standard_set',
            field=models.BooleanField(default=True, help_text='Включает стандартный набор (соус, имбирь, васаби)', verbose_name='Включает допы'),
        ),
    ]
