# Generated by Django 4.0 on 2026-02-20 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_dish_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='dish_priority',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ п/п'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, help_text="Порядковый номер отображения в категории, прим. '01'.\nПроставится автоматически.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ п/п'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='spicy_icon',
            field=models.BooleanField(default=False, verbose_name='🌶️ Иконка острое'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='vegan_icon',
            field=models.BooleanField(default=False, verbose_name='🌿 Иконка веган'),
        ),
        migrations.AddConstraint(
            model_name='dishcategory',
            constraint=models.UniqueConstraint(fields=('category', 'dish_priority'), name='unique_priority_in_category'),
        ),
    ]
