# Generated by Django 4.0 on 2026-02-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_dish_includes_standard_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='spicy_icon',
            field=models.BooleanField(default=False, verbose_name='Иконка острое'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='vegan_icon',
            field=models.BooleanField(default=False, verbose_name='Иконка веган'),
        ),
    ]
