# Generated by Django 4.0 on 2026-02-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_dish_includes_standard_set_and_more'),
        ('catalog', '0018_alter_dish_spicy_icon_alter_dish_vegan_icon'),
    ]

    operations = [
    ]
