# Generated by Django 4.0 on 2026-02-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_merge_20260220_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='includes_standard_set',
            field=models.BooleanField(default=True, help_text='Включает стандартный набор (соус, имбирь, васаби)\nОтображается в карточке блюда.', verbose_name='Включает допы'),
        ),
    ]
