# Generated by Django 4.0 on 2026-02-20 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_dish_includes_standard_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcategory',
            name='dish_priority',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text="Порядковый номер отображения в категории, прим. '01'.\nПроставится автоматически.", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ п/п'),
        ),
    ]
