# Generated by Django 4.0 on 2026-03-19 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_dish_final_price_alter_dish_final_price_p1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text="Порядковый номер отображения в категории, прим. '01'.\nПроставится автоматически.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ п/п'),
        ),
    ]
