# Generated by Django 4.0 on 2026-03-19 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_dish_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, help_text="Порядковый номер отображения в категории, прим. '01'.\nПроставится автоматически.", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ п/п'),
        ),
    ]
