# Generated by Django 4.0 on 2026-04-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_dish_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='utensils',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Кол-во приборов в порции.', verbose_name='приборы'),
        ),
    ]
