# Generated by Django 4.0 on 2026-06-30 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_dish_utensils'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishPartnerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], db_index=True, max_length=20, verbose_name='город')),
                ('source', models.CharField(choices=[('P1-1', 'Glovo'), ('P1-2', 'Wolt'), ('P2-1', 'Smoke'), ('P2-2', 'Не та дверь'), ('P3-1', 'Seal Tea'), ('1', 'внутренний'), ('3', 'TM_Bot'), ('4', 'сайт')], db_index=True, max_length=20, verbose_name='партнер / источник')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='финальная цена партнера, DIN')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_prices', to='catalog.dish', verbose_name='блюдо')),
            ],
            options={
                'verbose_name': 'цена блюда / город / партнер',
                'verbose_name_plural': 'цены блюд / города / партнеры',
                'ordering': ('dish', 'city', 'source'),
            },
        ),
        migrations.CreateModel(
            name='DishCityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], db_index=True, max_length=20, verbose_name='город')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='базовая цена сайта, DIN')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='скидка сайта, %')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='финальная цена сайта, DIN')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_prices', to='catalog.dish', verbose_name='блюдо')),
            ],
            options={
                'verbose_name': 'цена блюда / город / сайт',
                'verbose_name_plural': 'цены блюд / города / сайт',
                'ordering': ('dish', 'city'),
            },
        ),
        migrations.AddConstraint(
            model_name='dishpartnerprice',
            constraint=models.UniqueConstraint(fields=('dish', 'city', 'source'), name='unique_dish_city_partner_price'),
        ),
        migrations.AddConstraint(
            model_name='dishcityprice',
            constraint=models.UniqueConstraint(fields=('dish', 'city'), name='unique_dish_city_site_price'),
        ),
    ]
