# Generated by Django 4.0 on 2026-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_dishpartnerprice_dishcityprice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishcityprice',
            options={'ordering': ('dish', 'city'), 'verbose_name': 'цена блюда', 'verbose_name_plural': 'цены меню'},
        ),
        migrations.AlterModelOptions(
            name='dishpartnerprice',
            options={'ordering': ('dish', 'city', 'partner_category'), 'verbose_name': 'цена партнеров', 'verbose_name_plural': 'цены партнеров'},
        ),
        migrations.RemoveConstraint(
            model_name='dishpartnerprice',
            name='unique_dish_city_partner_price',
        ),
        migrations.RemoveField(
            model_name='dishpartnerprice',
            name='source',
        ),
        migrations.AddField(
            model_name='dishpartnerprice',
            name='partner_category',
            field=models.CharField(choices=[('P1', 'P1 - Glovo/Wolt'), ('P2', 'P2 - Smoke/Не та дверь/Seal Tea')], default='P1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='dishpartnerprice',
            constraint=models.UniqueConstraint(fields=('dish', 'city', 'partner_category'), name='unique_partner_price'),
        ),
    ]
