# Generated by Django 4.0 on 2026-07-04 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_dishcityprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishPriceMatrixProxy',
            fields=[
            ],
            options={
                'verbose_name': 'матрица цен',
                'verbose_name_plural': 'матрица цен',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dish',),
        ),
        migrations.AlterField(
            model_name='dishcityprice',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='финальная цена сайта, DIN'),
        ),
        migrations.AlterField(
            model_name='dishcityprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='базовая цена сайта, DIN'),
        ),
        migrations.AlterField(
            model_name='dishpartnerprice',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='финальная цена партнера, DIN'),
        ),
    ]
