# Generated by Django 4.0 on 2026-07-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_dishpricematrixproxy_alter_dishcityprice_final_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishcityprice',
            options={'ordering': ('dish', 'city'), 'permissions': [('change_citydishprice_Beograd', 'Can change city dish price Beograd'), ('change_citydishprice_NoviSad', 'Can change city dish price NoviSad')], 'verbose_name': 'цена блюда', 'verbose_name_plural': 'цены меню'},
        ),
        migrations.AlterModelOptions(
            name='dishpartnerprice',
            options={'ordering': ('dish', 'city', 'partner_category'), 'permissions': [('change_partnerdishprice_Beograd', 'Can change partner dish price Beograd'), ('change_partnerdishprice_NoviSad', 'Can change partner dish price NoviSad')], 'verbose_name': 'цена партнеров', 'verbose_name_plural': 'цены партнеров'},
        ),
    ]
