# Generated by Django 4.0 on 2026-07-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_dishcityprice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='final_price_p1',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='final_price_p2',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
    ]
