# Generated by Django 4.0 on 2024-06-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('open_time', models.TimeField(verbose_name='открытие')),
                ('close_time', models.DateTimeField(verbose_name='закрытие')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
