# Generated by Django 4.0 on 2024-06-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinesettings',
            name='close_time',
            field=models.TimeField(verbose_name='закрытие'),
        ),
    ]
