# Generated by Django 4.0 on 2024-09-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_onlinesettings_close_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineSettings',
        ),
    ]
