# Generated by Django 4.0 on 2024-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rus', models.CharField(max_length=100, verbose_name='заголовок рус')),
                ('promocode', models.CharField(max_length=6, verbose_name='код')),
                ('discount', models.CharField(max_length=5, verbose_name='скидка')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Окончание действия')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rus', models.CharField(max_length=100, verbose_name='заголовок рус')),
                ('full_text_rus', models.TextField(max_length=600, verbose_name='описание рус')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок en')),
                ('full_text_en', models.TextField(blank=True, max_length=600, null=True, verbose_name='описание en')),
                ('title_srb', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок srb')),
                ('full_text_srb', models.TextField(blank=True, max_length=600, null=True, verbose_name='описание srb')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='город')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('image_rus', models.ImageField(blank=True, default=None, null=True, upload_to='promo/', verbose_name='Изображение')),
                ('image_en', models.ImageField(blank=True, default=None, null=True, upload_to='promo/', verbose_name='Изображение')),
                ('image_srb', models.ImageField(blank=True, default=None, null=True, upload_to='promo/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'промо-новость',
                'verbose_name_plural': 'промо-новости',
                'ordering': ['-created'],
            },
        ),
    ]
