# Generated by Django 4.0 on 2024-02-09 11:57

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rus', models.CharField(max_length=100, verbose_name='заголовок рус')),
                ('promocode', models.CharField(max_length=6, verbose_name='код')),
                ('discount', models.CharField(max_length=5, verbose_name='скидка')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Окончание действия')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='город')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='изображение ru')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='изображение en')),
                ('image_sr', models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='изображение sr')),
            ],
            options={
                'verbose_name': 'промо-новость',
                'verbose_name_plural': 'промо-новости',
                'ordering': ['-created'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromoNewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок')),
                ('full_text', models.TextField(blank=True, max_length=600, null=True, verbose_name='описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='promos.promonews')),
            ],
            options={
                'verbose_name': 'промо-новость Translation',
                'db_table': 'promos_promonews_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
