# Generated by Django 4.0 on 2024-03-26 11:28

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Окончание действия')),
                ('is_used', models.BooleanField(default=False, verbose_name='использован')),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Окончание действия')),
                ('title_rus', models.CharField(max_length=100, verbose_name='заголовок рус')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='код')),
                ('ttl_am_discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text="Внесите скидку, прим. для 10% внесите '10,00'.", max_digits=7, null=True, verbose_name='Скидка на весь заказ, %')),
                ('ttl_am_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Внесите скидку, прим. '300,00'.", max_digits=7, null=True, verbose_name='Скидка на весь заказ, DIN')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
                ('gift', models.BooleanField(default=False, verbose_name='Подарок')),
                ('gift_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание подарка')),
                ('first_order', models.BooleanField(default=False, verbose_name='Первый заказ')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
                'ordering': ['-created'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('city', models.CharField(choices=[('Beograd', 'Beograd'), ('Novi_sad', 'Novi Sad')], max_length=20, verbose_name='город')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='изображение ru')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='изображение en')),
                ('image_sr_latn', models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='изображение sr-latn')),
            ],
            options={
                'verbose_name': 'промо-новость',
                'verbose_name_plural': 'промо-новости',
                'ordering': ['-created'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromoNewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.TextField(blank=True, max_length=100, null=True, verbose_name='заголовок')),
                ('full_text', models.TextField(blank=True, max_length=600, null=True, verbose_name='описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='promos.promonews')),
            ],
            options={
                'verbose_name': 'промо-новость Translation',
                'db_table': 'promos_promonews_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromocodeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='promos.promocode')),
            ],
            options={
                'verbose_name': 'промокод Translation',
                'db_table': 'promos_promocode_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
