# Generated by Django 4.0 on 2024-04-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created'], 'verbose_name': 'promocode', 'verbose_name_plural': 'promocodes'},
        ),
        migrations.AlterModelOptions(
            name='promocodetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'promocode Translation'},
        ),
    ]
