# Generated by Django 4.0 on 2024-03-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatpromocode',
            name='base_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baseprofile', verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='privatpromocode',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promos.promocode', verbose_name='промокод'),
        ),
        migrations.AlterUniqueTogether(
            name='promonewstranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='promocodetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
