# Generated by Django 4.0 on 2024-01-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promonews',
            name='full_text_eng',
        ),
        migrations.RemoveField(
            model_name='promonews',
            name='title_eng',
        ),
        migrations.AddField(
            model_name='promonews',
            name='full_text_en',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='описание en'),
        ),
        migrations.AddField(
            model_name='promonews',
            name='image_en',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='promo/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='promonews',
            name='image_rus',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='promo/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='promonews',
            name='image_srb',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='promo/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='promonews',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок en'),
        ),
    ]
