# Generated by Django 4.0 on 2024-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promonews',
            name='image_sr',
        ),
        migrations.AddField(
            model_name='promonews',
            name='image_sr_latn',
            field=models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='изображение sr-latn'),
        ),
    ]
