# Generated by Django 4.0 on 2024-04-07 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('promos', '0002_alter_promocode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatpromocode',
            name='base_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.baseprofile', verbose_name='пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatpromocode',
            name='promocode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='promos.promocode', verbose_name='промокод'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Внесите цену в RSD. Формат 00000.00', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='MIN сумма заказа, RSD'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='promonewstranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
