# Generated by Django 4.0 on 2024-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0002_remove_promonews_image_sr_promonews_image_sr_latn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promonews',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('Novi_sad', 'Novi Sad')], default='Beograd', max_length=20, verbose_name='город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promonewstranslation',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='заголовок'),
        ),
    ]
