# Generated by Django 4.0 on 2024-03-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0003_alter_promonews_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Внесите скидку, прим. для 10% внесите '10,00'.", max_digits=7, null=True, verbose_name='Скидка, %'),
        ),
    ]
