# Generated by Django 4.0 on 2024-04-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0003_privatpromocode_base_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatpromocode',
            options={'ordering': ['-created'], 'verbose_name': 'privat_promocode', 'verbose_name_plural': 'privat_promocodes'},
        ),
    ]
