# Generated by Django 4.0 on 2024-03-31 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0003_alter_promocode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Внесите цену в RSD. Формат 00000.00', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='MIN сумма заказа, RSD'),
        ),
    ]
