# Generated by Django 4.0 on 2024-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0004_alter_privatpromocode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promonews',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd')], max_length=20, verbose_name='город'),
        ),
    ]
