# Generated by Django 4.0 on 2024-03-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_webaccount_notes'),
        ('promos', '0004_alter_promocode_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Окончание действия')),
                ('is_used', models.BooleanField(default=False, verbose_name='использован')),
                ('base_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baseprofile', verbose_name='пользователь')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promos.promocode', verbose_name='промокод')),
            ],
        ),
    ]
