# Generated by Django 4.0 on 2024-06-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0005_alter_promonews_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promonews',
            name='image_en',
            field=models.FileField(blank=True, null=True, upload_to='promo/', verbose_name='изображение en'),
        ),
        migrations.AlterField(
            model_name='promonews',
            name='image_ru',
            field=models.FileField(blank=True, null=True, upload_to='promo/', verbose_name='изображение ru'),
        ),
        migrations.AlterField(
            model_name='promonews',
            name='image_sr_latn',
            field=models.FileField(blank=True, null=True, upload_to='promo/', verbose_name='изображение sr-latn'),
        ),
    ]
