# Generated by Django 4.0 on 2024-06-15 21:55

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0006_alter_promonews_image_en_alter_promonews_image_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promonewstranslation',
            name='full_text',
            field=django_summernote.fields.SummernoteTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promonewstranslation',
            name='title',
            field=django_summernote.fields.SummernoteTextField(default=''),
            preserve_default=False,
        ),
    ]
