# Generated by Django 4.0 on 2025-02-18 19:05

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0006_alter_promonews_image_en_alter_promonews_image_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promonews',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], max_length=20, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='promonewstranslation',
            name='full_text',
            field=django_summernote.fields.SummernoteTextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promonewstranslation',
            name='title',
            field=django_summernote.fields.SummernoteTextField(default='title'),
            preserve_default=False,
        ),
    ]
