# Generated by Django 4.0 on 2024-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0007_alter_promonewstranslation_full_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promonews',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], max_length=20, verbose_name='город'),
        ),
    ]
