# Generated by Django 4.0 on 2025-11-08 11:33

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0007_alter_promonews_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', django_summernote.fields.SummernoteTextField(help_text='Текст, который уйдёт в Telegram.', verbose_name='Текст сообщения')),
                ('disable_link_preview', models.BooleanField(default=False, help_text='Если включено — Telegram не будет показывать превью для ссылок.', verbose_name='Отключить превью ссылок')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sending', 'Отправляется'), ('done', 'Отправлено'), ('error', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('total_recipients', models.PositiveIntegerField(default=0, editable=False, verbose_name='Всего получателей')),
                ('delivered_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Доставлено')),
            ],
            options={
                'verbose_name': 'Рассылка (промо)',
                'verbose_name_plural': 'Рассылки (промо)',
                'ordering': ('-created_at',),
            },
        ),
    ]
