# Generated by Django 4.0 on 2025-11-09 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0019_messengeraccount_can_write'),
        ('promos', '0008_promobroadcast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promobroadcast',
            options={'ordering': ('-created_at',), 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='promobroadcast',
            name='bot',
            field=models.ForeignKey(default=1, help_text='Через какого бота выполнять рассылку', on_delete=django.db.models.deletion.PROTECT, related_name='promo_broadcasts', to='tm_bot.ordersbot', verbose_name='Бот'),
            preserve_default=False,
        ),
    ]
