# Generated by Django 4.0 on 2025-11-10 12:26

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tm_bot', '0019_messengeraccount_can_write'),
        ('promos', '0009_alter_promobroadcast_options_promobroadcast_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('city', models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], default='Beograd', max_length=20, verbose_name='город *')),
                ('link', models.URLField(blank=True, help_text='Ссылка на бота со стартовым параметром (вносится автоматически).', null=True, verbose_name='Текст ссылки на рекламу')),
                ('new_users', models.IntegerField(blank=True, null=True, verbose_name='Новых пользователей')),
                ('bot', models.ForeignKey(help_text='Для какого бота сгенерирован источник', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='tm_bot.ordersbot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='promobroadcast',
            name='body',
            field=django_summernote.fields.SummernoteTextField(help_text="Текст рассылки для Telegram. Допустимое форматирование:\n• Жирный '<b></b>'\n• Курсив '<i></i>'\n• Подчёркивание '<u></u>'\n• Ссылки '<a></a>'\n\n⚠️ Другие HTML-теги не поддерживаются Telegram и будут автоматически удалены.", verbose_name='Текст сообщения'),
        ),
        migrations.CreateModel(
            name='CampaignOpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_events', to='promos.campaign', verbose_name='источник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_events', to='tm_bot.messengeraccount', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'переход',
                'verbose_name_plural': 'переходы',
            },
        ),
    ]
