# Generated by Django 4.0 on 2025-11-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0010_campaign_alter_promobroadcast_body_campaignopenevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatpromocode',
            options={'ordering': ['-created'], 'verbose_name': 'Промокод личн', 'verbose_name_plural': 'Промокоды личн'},
        ),
        migrations.AlterModelOptions(
            name='promonews',
            options={'ordering': ['-created'], 'verbose_name': 'новость на сайте', 'verbose_name_plural': 'Новости на сайте'},
        ),
        migrations.AlterModelOptions(
            name='promonewstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'новость на сайте Translation'},
        ),
    ]
