# Generated by Django 4.0 on 2025-12-10 08:25

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0011_alter_privatpromocode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobroadcast',
            name='image',
            field=models.ImageField(blank=True, help_text='Опционально. Если указана только картинка — уйдёт только фото. Если картинка и текст — текст будет подписью (caption).\nРекомендуемые форматы: JPG или PNG, до ~5 МБ.', null=True, upload_to='promo_broadcasts/', verbose_name='Картинка для рассылки'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название кампании'),
        ),
        migrations.AlterField(
            model_name='promobroadcast',
            name='body',
            field=django_summernote.fields.SummernoteTextField(help_text='Текст рассылки для Telegram. Допустимое форматирование:<br>• Жирный &#x27;&lt;b&gt;&lt;/b&gt;&#x27;     • Подчёркивание &#x27;&lt;u&gt;&lt;/u&gt;&#x27;<br>• Курсив &#x27;&lt;i&gt;&lt;/i&gt;&#x27;     • Ссылки &#x27;&lt;a&gt;&lt;/a&gt;&#x27;<br><br>⚠️ Другие HTML-теги не поддерживаются Telegram и будут автоматически удалены.', verbose_name='Текст сообщения'),
        ),
    ]
