# Generated by Django 4.0 on 2025-12-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0012_promobroadcast_image_alter_campaign_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobroadcast',
            name='add_keyboard_button',
            field=models.BooleanField(default=False, help_text='Если включено — к сообщению прикрепятся заданные кнопки (писать кодом)', verbose_name='Добавить keyboard-кнопки к рассылке'),
        ),
    ]
