# Generated by Django 4.0 on 2025-12-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0013_promobroadcast_add_keyboard_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promobroadcast',
            name='add_keyboard_button',
        ),
        migrations.AddField(
            model_name='promobroadcast',
            name='add_inline_keyboard',
            field=models.BooleanField(default=False, help_text='Если включено — под сообщением прикрепятся заданные кнопки (писать кодом)', verbose_name='Добавить inline клавиатуру'),
        ),
        migrations.AddField(
            model_name='promobroadcast',
            name='add_reply_keyboard',
            field=models.BooleanField(default=False, help_text='Если включено — при получении сообщения внизу экрана появятся кнопки (писать кодом)', verbose_name='Добавить reply клавиатуру'),
        ),
    ]
