# Generated by Django 4.0 on 2025-12-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0014_remove_promobroadcast_add_keyboard_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobroadcast',
            name='processed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пользователей обработано'),
        ),
        migrations.AddField(
            model_name='promobroadcast',
            name='results_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Результат рассылки'),
        ),
        migrations.AlterField(
            model_name='promobroadcast',
            name='title',
            field=models.CharField(help_text='Для отображения в админке.', max_length=255, verbose_name='Заголовок'),
        ),
    ]
