# Generated by Django 4.0 on 2026-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0015_promobroadcast_processed_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobroadcast',
            name='title',
            field=models.CharField(help_text='Внутреннее название рассылки для отображения в админке.', max_length=255, verbose_name='Название'),
        ),
    ]
