# Generated by Django 4.0 on 2026-04-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0016_alter_promobroadcast_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobroadcast',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='broadcast_reports/', verbose_name='Отчет по рассылке'),
        ),
    ]
