# Generated by Django 4.0 on 2026-04-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_dish_utensils'),
        ('promos', '0017_promobroadcast_report_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Только для админки, не отображается на сайте.', max_length=200, verbose_name='название (внутреннее)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='изображение баннера')),
                ('city', models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], db_index=True, max_length=40, verbose_name='город')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, help_text='Чем меньше число — тем раньше показывается.', verbose_name='порядок')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('show_in_miniapp', models.BooleanField(default=True, verbose_name='показывать в Telegram Mini App')),
                ('show_on_site', models.BooleanField(default=True, verbose_name='показывать на сайте (моб)')),
                ('action_type', models.CharField(choices=[('dish', 'Блюдо (карточка)'), ('category', 'Категория/подборка'), ('promo_page', 'Промо/новость (внутренняя страница)'), ('external', 'Внешняя ссылка'), ('modal_svg', 'Модальное окно (SVG-контент)'), ('none', 'Некликабельный')], default='none', max_length=20, verbose_name='действие')),
                ('promo_slug', models.SlugField(blank=True, max_length=100, verbose_name='slug промо-страницы')),
                ('external_url', models.URLField(blank=True, help_text='Instagram, Google Maps, Telegram и т.п.', verbose_name='внешняя ссылка')),
                ('modal_svg', models.FileField(blank=True, upload_to='banners/svg/', verbose_name='SVG для модального окна')),
                ('active_from', models.DateTimeField(blank=True, null=True, verbose_name='показывать с')),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='показывать до')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.category', verbose_name='категория')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.dish', verbose_name='блюдо')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
                'ordering': ['city', 'priority'],
            },
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(fields=('city', 'priority'), name='unique_banner_priority_per_city'),
        ),
    ]
