# Generated by Django 4.0 on 2026-04-02 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_dish_utensils'),
        ('promos', '0018_banner_banner_unique_banner_priority_per_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='modal_image',
            field=models.ImageField(blank=True, help_text='Картинка-постер, открывается поверх страницы при клике.<br><b>Размер:</b> 1080×1920 px или 900×1200 px.<br><b>Соотношение сторон:</b> 3:4 или 9:16 (вертикальное).<br><b>Формат:</b> JPG или PNG — конвертируется в WebP автоматически.<br><b>Вес файла:</b> до 500 KB.<br><b>Важно:</b> внизу оставьте ~100 px свободного места под кнопку закрытия.<br>Заполните <b>modal_svg</b> или <b>modal_image</b> (не оба сразу).', null=True, upload_to='banners/modal/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='картинка для модального окна'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='action_type',
            field=models.CharField(choices=[('dish', 'Блюдо — открыть карточку'), ('category', 'Категория — открыть список'), ('promo_page', 'Промо-страница (внутренняя)'), ('external', 'Внешняя ссылка'), ('modal_svg', 'Модальное окно (SVG или картинка)'), ('none', 'Некликабельный')], default='none', max_length=20, verbose_name='действие при клике'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Заполните если action_type = «Категория».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='dish',
            field=models.ForeignKey(blank=True, help_text='Заполните если action_type = «Блюдо».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.dish', verbose_name='блюдо'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='external_url',
            field=models.URLField(blank=True, help_text='Заполните если action_type = «Внешняя ссылка».<br>Примеры: Instagram, Google Maps, Telegram-канал.', verbose_name='внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Квадратная карточка в карусели баннеров.<br><b>Размер:</b> 600×600 px (минимум 400×400 px).<br><b>Соотношение сторон:</b> 1:1 (квадрат, допуск ±15%).<br><b>Формат:</b> JPG или PNG — конвертируется в WebP автоматически.<br><b>Вес файла:</b> до 300 KB.<br><b>Важно:</b> ключевой контент размещайте в центре с отступом ~15% от каждого края.', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='изображение баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='modal_svg',
            field=models.FileField(blank=True, help_text='SVG-файл с зашитым контентом (текст + картинки).<br>Используется для промо-страниц типа /promo — условия акций, ДР и т.п. Файл готовит дизайнер.<br>Заполните <b>modal_svg</b> или <b>modal_image</b> (не оба сразу).', null=True, upload_to='banners/svg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='SVG для модального окна'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Чем меньше число — тем раньше показывается.', verbose_name='порядок в карусели'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='promo_slug',
            field=models.SlugField(blank=True, help_text='Заполните если action_type = «Промо-страница».<br>Пример: "birthday" → /promo/birthday/', max_length=100, verbose_name='slug промо-страницы'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='show_on_site',
            field=models.BooleanField(default=True, verbose_name='показывать на сайте (мобильная версия)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлён'),
        ),
    ]
