# Generated by Django 4.0 on 2026-04-03 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0019_banner_modal_image_alter_banner_action_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='modal_image',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Квадратная карточка в карусели баннеров.<br><b>Размер:</b> 600×600 px (минимум 400×400 px).<br><b>Соотношение сторон:</b> 1:1 (квадрат, допуск ±15%).<br><b>Формат:</b> JPG или PNG — конвертируется в WebP автоматически.<br><b>Вес файла:</b> до 300 KB.<br><b>Важно:</b> ключевой контент размещайте в центре с отступом ~15% от каждого края.', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='баннер'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='modal_svg',
            field=models.FileField(blank=True, help_text='SVG-файл с зашитым контентом (текст + картинки).<br>Используется для промо-страниц типа /promo — условия акций, ДР и т.п. Файл готовит дизайнер.<br>', null=True, upload_to='banners/svg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='SVG для модального окна'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Чем меньше число — тем раньше показывается.', null=True, verbose_name='порядок в карусели'),
        ),
    ]
