# Generated by Django 4.0 on 2026-04-06 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0020_remove_banner_modal_image_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_en',
            field=models.ImageField(blank=True, help_text='Переопределение для английского языка.<br>Квадратная карточка в карусели баннеров.<br><b>Размер:</b> 600×600 px (минимум 400×400 px).<br><b>Соотношение сторон:</b> 1:1 (квадрат, допуск ±15%).<br><b>Формат:</b> JPG или PNG — конвертируется в WebP автоматически.<br><b>Вес файла:</b> до 500 KB.<br><b>Важно:</b> ключевой контент размещайте в центре с отступом ~15% от каждого края.', null=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='баннер en'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_ru',
            field=models.ImageField(blank=True, help_text='Переопределение для русского языка.<br>Квадратная карточка в карусели баннеров.<br><b>Размер:</b> 600×600 px (минимум 400×400 px).<br><b>Соотношение сторон:</b> 1:1 (квадрат, допуск ±15%).<br><b>Формат:</b> JPG или PNG — конвертируется в WebP автоматически.<br><b>Вес файла:</b> до 500 KB.<br><b>Важно:</b> ключевой контент размещайте в центре с отступом ~15% от каждого края.', null=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='баннер ru'),
        ),
        migrations.AddField(
            model_name='banner',
            name='modal_svg_en',
            field=models.FileField(blank=True, help_text='Переопределение для английского языка.<br>SVG-файл с зашитым контентом (текст + картинки).<br>Используется для промо-страниц типа /promo — условия акций, ДР и т.п. Файл готовит дизайнер.<br>', null=True, upload_to='banners/svg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='SVG модального окна en'),
        ),
        migrations.AddField(
            model_name='banner',
            name='modal_svg_ru',
            field=models.FileField(blank=True, help_text='Переопределение для русского языка.<br>SVG-файл с зашитым контентом (текст + картинки).<br>Используется для промо-страниц типа /promo — условия акций, ДР и т.п. Файл готовит дизайнер.<br>', null=True, upload_to='banners/svg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='SVG модального окна ru'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='<b>Дефолтная картинка (сербский).</b> Используется для всех языков, если не загружены ru/en варианты.<br>Квадратная карточка в карусели баннеров.<br><b>Размер:</b> 600×600 px (минимум 400×400 px).<br><b>Соотношение сторон:</b> 1:1 (квадрат, допуск ±15%).<br><b>Формат:</b> JPG или PNG — конвертируется в WebP автоматически.<br><b>Вес файла:</b> до 500 KB.<br><b>Важно:</b> ключевой контент размещайте в центре с отступом ~15% от каждого края.', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='баннер (sr — дефолт)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='modal_svg',
            field=models.FileField(blank=True, help_text='<b>Дефолтный SVG (сербский).</b> Используется для всех языков, если не загружены ru/en варианты.<br>SVG-файл с зашитым контентом (текст + картинки).<br>Используется для промо-страниц типа /promo — условия акций, ДР и т.п. Файл готовит дизайнер.<br>', null=True, upload_to='banners/svg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='SVG модального окна (sr — дефолт)'),
        ),
    ]
