# Generated by Django 4.0 on 2026-04-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0021_banner_image_en_banner_image_ru_banner_modal_svg_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='show_in_miniapp',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='show_on_site',
        ),
    ]
