# Generated by Django 4.0 on 2026-05-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0022_remove_banner_show_in_miniapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='promo_slug',
        ),
        migrations.AddField(
            model_name='banner',
            name='promo_news',
            field=models.ForeignKey(blank=True, help_text='Заполните если action_type = «Промо-страница».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='promos.promonews', verbose_name='промо-страница'),
        ),
        migrations.AddField(
            model_name='promonews',
            name='slug',
            field=models.SlugField(default=1, help_text='Используется для ссылки вида /promo/<slug>/', max_length=100, unique=False, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
