# Generated by Django 4.0 on 2026-05-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0023_remove_banner_promo_slug_banner_promo_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='action_type',
            field=models.CharField(choices=[('dish', 'Блюдо — открыть карточку'), ('category', 'Категория — открыть список'), ('promo_news', 'Промо-страница (внутренняя)'), ('external', 'Внешняя ссылка'), ('modal_svg', 'Модальное окно (SVG или картинка)'), ('none', 'Некликабельный')], default='none', max_length=20, verbose_name='действие при клике'),
        ),
    ]
