# Generated by Django 4.0 on 2026-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0024_alter_banner_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promonews',
            name='slug',
            field=models.SlugField(help_text='Используется для ссылки вида /promo?<slug>/', max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
