# Generated by Django 4.0 on 2026-05-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0025_alter_promonews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promonews',
            name='slug',
            field=models.SlugField(help_text='Используется для ссылки вида /promo?news=<slug>/', max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
