# Generated by Django 4.0 on 2026-05-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0025_rename_min_сourier_payout_courier_min_payout'),
        ('promos', '0026_alter_promonews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='delivery_contacts.restaurant', verbose_name='ресторан'),
        ),
    ]
