# Generated by Django 4.0 on 2026-05-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0027_banner_restaurant'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(fields=('promo_news', 'city', 'restaurant'), name='unique_banner_promo_city_restaurant'),
        ),
    ]
