# Generated by Django 4.0 on 2026-06-29 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0028_banner_unique_banner_promo_city_restaurant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='banner',
            name='unique_banner_promo_city_restaurant',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='promo_news',
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='ссылка (внешняя/внутренняя)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='action_type',
            field=models.CharField(choices=[('dish', 'Блюдо — открыть карточку'), ('category', 'Категория — открыть список'), ('internal', 'Внутренняя ссылка'), ('external', 'Внешняя ссылка'), ('modal_svg', 'Модальное окно (SVG или картинка)'), ('none', 'Некликабельный')], default='none', max_length=20, verbose_name='действие при клике'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='<b>Дефолтная картинка (сербский).</b> Используется для всех языков, если не загружены ru/en варианты.<br>Квадратная карточка в карусели баннеров.<br><b>Размер:</b> 600×600 px (минимум 400×400 px).<br><b>Соотношение сторон:</b> 1:1 (квадрат, допуск ±15%).<br><b>Формат:</b> JPG или PNG — конвертируется в WebP автоматически.<br><b>Вес файла:</b> до 500 KB.<br><b>Важно:</b> ключевой контент размещайте в центре с отступом ~15% от каждого края.', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='баннер (SR — дефолт)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_en',
            field=models.ImageField(blank=True, help_text='Переопределение для английского языка.<br>Квадратная карточка в карусели баннеров.<br><b>Размер:</b> 600×600 px (минимум 400×400 px).<br><b>Соотношение сторон:</b> 1:1 (квадрат, допуск ±15%).<br><b>Формат:</b> JPG или PNG — конвертируется в WebP автоматически.<br><b>Вес файла:</b> до 500 KB.<br><b>Важно:</b> ключевой контент размещайте в центре с отступом ~15% от каждого края.', null=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='баннер EN'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_ru',
            field=models.ImageField(blank=True, help_text='Переопределение для русского языка.<br>Квадратная карточка в карусели баннеров.<br><b>Размер:</b> 600×600 px (минимум 400×400 px).<br><b>Соотношение сторон:</b> 1:1 (квадрат, допуск ±15%).<br><b>Формат:</b> JPG или PNG — конвертируется в WebP автоматически.<br><b>Вес файла:</b> до 500 KB.<br><b>Важно:</b> ключевой контент размещайте в центре с отступом ~15% от каждого края.', null=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='баннер RU'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='modal_svg',
            field=models.FileField(blank=True, help_text='<b>Дефолтный SVG (сербский).</b> Используется для всех языков, если не загружены ru/en варианты.<br>Файл модального окна с промо-информацией: условия акции, ДР и т.п.<br><b>Форматы:</b> SVG, JPG, JPEG, PNG или WebP.<br><b>Рекомендуемый размер:</b> до 1200 px по ширине.<br><b>Вес файла:</b> желательно до 1–1.5 MB.<br><b>Важно:</b> файлы 2+ MB могут не загрузиться или работать нестабильно.<br>Используйте более лёгкие / low-resolution версии изображений.', null=True, upload_to='banners/svg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Файл модального окна (SR — дефолт)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='modal_svg_en',
            field=models.FileField(blank=True, help_text='Переопределение для английского языка.<br>Файл модального окна с промо-информацией: условия акции, ДР и т.п.<br><b>Форматы:</b> SVG, JPG, JPEG, PNG или WebP.<br><b>Рекомендуемый размер:</b> до 1200 px по ширине.<br><b>Вес файла:</b> желательно до 1–1.5 MB.<br><b>Важно:</b> файлы 2+ MB могут не загрузиться или работать нестабильно.<br>Используйте более лёгкие / low-resolution версии изображений.', null=True, upload_to='banners/svg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Файл модального окна EN'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='modal_svg_ru',
            field=models.FileField(blank=True, help_text='Переопределение для русского языка.<br>Файл модального окна с промо-информацией: условия акции, ДР и т.п.<br><b>Форматы:</b> SVG, JPG, JPEG, PNG или WebP.<br><b>Рекомендуемый размер:</b> до 1200 px по ширине.<br><b>Вес файла:</b> желательно до 1–1.5 MB.<br><b>Важно:</b> файлы 2+ MB могут не загрузиться или работать нестабильно.<br>Используйте более лёгкие / low-resolution версии изображений.', null=True, upload_to='banners/svg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Файл модального окна RU'),
        ),
    ]
