# Generated by Django 4.0 on 2026-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0029_remove_banner_unique_banner_promo_city_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, help_text='Укажите ссылку в зависимости от выбранного типа действия. <br>Для внешней ссылки — полный URL (например, https://example.com). <br>Для внутренней — относительную ссылку без домена (например, /menu или /catalog/pizza).', max_length=200, verbose_name='ссылка (внешняя/внутренняя)'),
        ),
    ]
