# Generated by Django 4.0 on 2026-07-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0030_alter_banner_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['city', 'priority'], 'permissions': [('edit_banners_Beograd', 'Can ADD/CHANGE/DELETE banners Beograd'), ('edit_banners_NoviSad', 'Can  NoviSad')], 'verbose_name': 'баннер', 'verbose_name_plural': 'баннеры'},
        ),
    ]
