# Generated by Django 4.0 on 2024-06-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('created',), 'verbose_name': 'Активность пользователей', 'verbose_name_plural': 'Активности пользователей'},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='timestamp',
            new_name='created',
        ),
    ]
