# Generated by Django 4.0 on 2024-06-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created',), 'verbose_name': 'Активность пользователей', 'verbose_name_plural': 'Активности пользователей'},
        ),
    ]
