# Generated by Django 4.0 on 2024-07-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_useraddress_address_alter_useraddress_flat_and_more'),
        ('audit', '0003_alter_auditlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='base_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.baseprofile'),
        ),
    ]
