# Generated by Django 4.0 on 2024-07-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_base_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(default='000', max_length=3),
            preserve_default=False,
        ),
    ]
