# Generated by Django 4.0 on 2024-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auditlog_ip_auditlog_ip_is_routable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
