# Generated by Django 4.0 on 2026-03-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('audit', '0007_alter_auditlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='endpoint',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
