# Generated by Django 4.0 on 2024-02-09 11:57

from decimal import Decimal

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Белград', 'Белград'), ('Нови_Сад', 'Нови_Сад')], max_length=20, verbose_name='город')),
                ('type', models.CharField(choices=[('delivery', 'Доставка'), ('takeaway', 'Самовывоз')], max_length=8, verbose_name='тип')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('min_order_price', models.FloatField(blank=True, null=True, verbose_name='min_цена_заказа')),
                ('default_delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Внесите цену в DIN. Формат 00000.00', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='цена, DIN')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name="Внесите скидку, прим. для 10% внесите '10,00'.")),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='contacts/', verbose_name='Карта районов доставки')),
            ],
            options={
                'verbose_name': 'доставка',
                'verbose_name_plural': 'способы доставки',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Белград', 'Белград'), ('Нови_Сад', 'Нови_Сад')], max_length=20, verbose_name='город')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('is_promo', models.BooleanField(default=False, verbose_name='промо')),
                ('promo_min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='мин сумма заказа, DIN')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='стоимость доставки, DIN')),
            ],
            options={
                'verbose_name': 'район доставки',
                'verbose_name_plural': 'районы доставки',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Белград', 'Белград'), ('Нови_Сад', 'Нови_Сад')], max_length=20, verbose_name='город')),
                ('short_name', models.CharField(max_length=20, verbose_name='название')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='координаты')),
                ('work_hours', models.CharField(max_length=100, verbose_name='время работы')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Внесите телефон, прим. '+38212345678'. Для пустого значения, внесите 'None'.", max_length=128, null=True, region=None, unique=True, verbose_name='телефон')),
                ('admin', models.CharField(blank=True, max_length=100, null=True, verbose_name='админ')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='contacts/', verbose_name='Изображение')),
                ('is_overloaded', models.BooleanField(default=False, verbose_name='перегружен')),
            ],
            options={
                'verbose_name': 'ресторан',
                'verbose_name_plural': 'рестораны',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='delivery_contacts.delivery')),
            ],
            options={
                'verbose_name': 'доставка Translation',
                'db_table': 'delivery_contacts_delivery_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
