# Generated by Django 4.0 on 2024-02-11 07:15

import datetime
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0002_alter_deliverytranslation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='min_order_price',
        ),
        migrations.AddField(
            model_name='delivery',
            name='max_time',
            field=models.TimeField(default=datetime.time(21, 30), verbose_name='MAX время доставки заказов *'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Внесите цену в DIN. Формат 00000.00', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='MIN_цена_заказа, DIN'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='min_time',
            field=models.TimeField(default=datetime.time(10, 30), verbose_name='MIN время доставки заказов *'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='city',
            field=models.CharField(choices=[('Белград', 'Белград'), ('Нови_Сад', 'Нови_Сад')], max_length=20, verbose_name='Город *'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='default_delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Внесите цену в DIN. Формат 00000.00', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Стоимость доставки по-умолчанию, DIN'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен *'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('takeaway', 'Самовывоз')], max_length=8, verbose_name='Тип *'),
        ),
    ]
