# Generated by Django 4.0 on 2024-01-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0002_alter_delivery_is_active_alter_shop_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Белград', 'Белград'), ('Нови_Сад', 'Нови_Сад')], max_length=20, verbose_name='район')),
                ('district', models.CharField(choices=[('1', 'Доставка'), ('2', 'Самовывоз')], max_length=20, unique=True, verbose_name='район')),
                ('promo', models.BooleanField(default=False, verbose_name='промо')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='мин сумма заказа, DIN')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='стоимость доставки, DIN')),
            ],
            options={
                'verbose_name': 'район доставки',
                'verbose_name_plural': 'районы доставки',
            },
        ),
    ]
