# Generated by Django 4.0 on 2024-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0003_districtdeliverycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='размер скидки'),
        ),
    ]
