# Generated by Django 4.0 on 2024-02-12 14:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0003_remove_delivery_min_order_price_delivery_max_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='default_delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Внесите цену в DIN. Формат 00000.00', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Стоимость доставки по-умолчанию, DIN'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='discount',
            field=models.FloatField(blank=True, help_text="Внесите скидку, прим. для 10% внесите '10,00'.", null=True, verbose_name='Скидка на самовывоз'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='max_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 30), null=True, verbose_name='MAX время заказа'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Внесите цену в DIN. Формат 00000.00', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='MIN сумма заказа, DIN'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='min_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 30), null=True, verbose_name='MIN время заказа'),
        ),
    ]
