# Generated by Django 4.0 on 2024-01-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0004_delivery_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtdeliverycost',
            name='city',
            field=models.CharField(choices=[('Белград', 'Белград'), ('Нови_Сад', 'Нови_Сад')], max_length=20, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='districtdeliverycost',
            name='district',
            field=models.CharField(choices=[('1', 'Novi Beograd'), ('2', 'Voždovac'), ('3', 'Zvezdara'), ('4', 'Zemun'), ('5', 'Palilula'), ('6', 'Stari Grad'), ('7', 'Dorćol'), ('8', 'Belgrad_na_vodi'), ('9', 'Savski_Venac'), ('10', 'другое')], max_length=20, unique=True, verbose_name='район'),
        ),
    ]
