# Generated by Django 4.0 on 2024-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0005_alter_delivery_city_alter_deliveryzone_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default='22:00', verbose_name='время закрытия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(default='10:00', verbose_name='время открытия'),
            preserve_default=False,
        ),
    ]
