# Generated by Django 4.0 on 2024-01-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0005_alter_districtdeliverycost_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtdeliverycost',
            name='district',
            field=models.CharField(max_length=20, unique=True, verbose_name='район'),
        ),
    ]
