# Generated by Django 4.0 on 2024-01-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0006_alter_districtdeliverycost_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'доставка', 'verbose_name_plural': 'доставки'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='contacts/', verbose_name='Карта районов доставки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='contacts/', verbose_name='Изображение'),
        ),
    ]
