# Generated by Django 4.0 on 2024-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0006_remove_restaurant_work_hours_restaurant_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Внесите скидку, прим. для 10% внесите '10,00'.", max_digits=7, null=True, verbose_name='Скидка на самовывоз, %'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='PROMO'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='promo_min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PROMO мин сумма заказа, DIN'),
        ),
    ]
