# Generated by Django 4.0 on 2024-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0007_alter_delivery_discount_alter_deliveryzone_is_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='ПО ДЕФОЛТУ'),
        ),
    ]
