# Generated by Django 4.0 on 2024-03-09 08:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0008_restaurant_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
