# Generated by Django 4.0 on 2024-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0009_alter_deliveryzone_polygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Beograd', 'Beograd'), ('Novi_sad', 'Novi Sad')], max_length=20, verbose_name='город')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
            ],
        ),
    ]
