# Generated by Django 4.0 on 2024-05-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0011_courier_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'verbose_name': 'зона доставки', 'verbose_name_plural': 'зоны доставки'},
        ),
    ]
