# Generated by Django 4.0 on 2024-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0012_alter_deliveryzone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd')], max_length=20, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd')], max_length=20, verbose_name='Город *'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd')], max_length=20, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd')], max_length=20, verbose_name='город'),
        ),
    ]
