# Generated by Django 4.0 on 2024-08-14 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0014_alter_delivery_max_time_alter_delivery_min_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='max_acc_time',
            field=models.TimeField(blank=True, default=datetime.time(22, 0), help_text='MAX время приема заказов на доставку', null=True, verbose_name='MAX время заказа'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='min_acc_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 0), help_text='MIN время приема заказов на доставку', null=True, verbose_name='MIN время заказа'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], max_length=20, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], max_length=20, verbose_name='Город *'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='max_time',
            field=models.TimeField(blank=True, default=datetime.time(22, 0), null=True, verbose_name='MAX время выдачи'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='min_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 0), null=True, verbose_name='MIN время выдачи'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], max_length=20, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], max_length=20, verbose_name='город'),
        ),
    ]
