# Generated by Django 4.0 on 2024-08-28 22:02

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0018_alter_delivery_max_acc_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytranslation',
            name='description',
            field=django_summernote.fields.SummernoteTextField(default='Free delivery Stari Grad, Dorchol, Vrachar, Begrade na vodi'),
            preserve_default=False,
        ),
    ]
