# Generated by Django 4.0 on 2024-09-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0019_alter_deliverytranslation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='admin',
        ),
    ]
