# Generated by Django 4.0 on 2024-09-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0020_remove_restaurant_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='city',
            field=models.CharField(blank=True, choices=[('Beograd', 'Beograd'), ('NoviSad', 'Novi Sad')], max_length=20, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='ПО ДЕФОЛТУ для города'),
        ),
    ]
