# Generated by Django 4.0 on 2024-09-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0022_alter_delivery_max_acc_time_alter_delivery_max_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ('id',), 'verbose_name': 'зона доставки', 'verbose_name_plural': 'зоны доставки'},
        ),
    ]
