# Generated by Django 4.0 on 2025-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0023_alter_deliveryzone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'курьер', 'verbose_name_plural': 'курьеры'},
        ),
        migrations.AddField(
            model_name='courier',
            name='min_сourier_payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Мин оплата за выход, DIN'),
        ),
    ]
