# Generated by Django 4.0 on 2025-02-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0024_alter_courier_options_courier_min_сourier_payout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='min_сourier_payout',
            new_name='min_payout',
        ),
    ]
