# Generated by Django 4.0 on 2026-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0025_rename_min_сourier_payout_courier_min_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('takeaway', 'Самовывоз'), ('restaurant', 'Ресторан')], max_length=15, verbose_name='Тип *'),
        ),
    ]
