# Generated by Django 4.0 on 2026-06-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_contacts', '0026_alter_delivery_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'способ получения', 'verbose_name_plural': 'способы получения'},
        ),
        migrations.AlterModelOptions(
            name='deliverytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'способ получения Translation'},
        ),
    ]
